'use strict';
(() => {
const E=PawnEngine,$=id=>document.getElementById(id),KEY='midnight-pawn-v3';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=x=>Math.round(x).toLocaleString('ko-KR');
let s,view='trade',stockFilter='all',codexMode='items',category='all',timer,audio,saveOK=true;
for(const key of [KEY,KEY+'-backup']){try{const candidate=JSON.parse(localStorage.getItem(key)||'null');if(E.validate(candidate)){s=E.prepare(candidate);break}}catch{}}if(!s)s=E.prepare(E.create());
const sheets=[];
function sheet(index){if(!sheets[index]){const img=new Image();img.decoding='async';img.onload=paintPeople;img.src='assets/characters-'+index+'.webp';sheets[index]=img}return sheets[index]}
function save(){try{const old=localStorage.getItem(KEY);if(old){try{if(E.validate(JSON.parse(old)))localStorage.setItem(KEY+'-backup',old)}catch{}}localStorage.setItem(KEY,JSON.stringify(s));saveOK=true}catch{saveOK=false;toast('저장 공간을 사용할 수 없어요. 창을 닫지 말아 주세요.')}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('toast').classList.remove('show'),2700)}
function tone(kind='tap'){if(!s.sound)return;try{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const now=audio.currentTime;const notes=kind==='rare'?[523,659,784,1046]:kind==='coin'?[784,1046]:[392];notes.forEach((hz,i)=>{const osc=audio.createOscillator(),gain=audio.createGain(),t=now+i*.07;osc.type='triangle';osc.frequency.value=hz;gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(.05,t+.009);gain.gain.exponentialRampToValueAtTime(.0001,t+.16);osc.connect(gain);gain.connect(audio.destination);osc.start(t);osc.stop(t+.18)})}catch{}}
function paintPeople(){for(const canvas of document.querySelectorAll('canvas[data-person]')){const id=Number(canvas.dataset.person),c=PAWN_CHARACTERS[id];if(!c)continue;const img=sheet(c.sheet);if(!img?.complete||!img.naturalWidth)continue;const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,canvas.width,canvas.height);const sw=img.naturalWidth/4,sh=img.naturalHeight/2;ctx.drawImage(img,(c.cell%4)*sw,Math.floor(c.cell/4)*sh,sw,sh,0,0,canvas.width,canvas.height)}}
function paintItems(){for(const canvas of document.querySelectorAll('canvas[data-item]'))PawnArt.item(canvas,E.item(canvas.dataset.item),Number(canvas.dataset.grade)||1,canvas.dataset.unknown==='true')}
function art(itemId,grade=1,cls='',unknown=false){return '<canvas class="'+cls+'" width="64" height="64" data-item="'+esc(itemId)+'" data-grade="'+grade+'" data-unknown="'+unknown+'" aria-hidden="true"></canvas>'}
function portrait(index,cls=''){return '<canvas class="'+cls+'" width="192" height="256" data-person="'+index+'" aria-hidden="true"></canvas>'}
function badge(grade,text){return '<span class="grade-badge" style="--grade:'+E.GRADES[grade][1]+'">'+esc(text||E.GRADES[grade][0])+'</span>'}
function run(fn,...args){const result=fn(s,...args);if(result?.ok===false){toast(result.message);return result}tone(fn===E.buy&&s.current.grade>=3?'rare':fn===E.sell?'coin':'tap');render();if(result?.message)toast(result.message);if(s.notices.length){const notice=s.notices.pop();s.notices=[];setTimeout(()=>toast(notice),900)}save();if(fn===E.buy&&innerWidth<=760)requestAnimationFrame(()=>document.getElementById('reveal-view').scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'}));return result}
function switchView(next){if(!['trade','stock','codex','shop'].includes(next))return;view=next;for(const el of document.querySelectorAll('.view'))el.classList.toggle('active',el.id==='view-'+view);for(const el of document.querySelectorAll('[data-view]')){el.classList.toggle('active',el.dataset.view===view);if(el.dataset.view===view)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current')}render();window.scrollTo({top:0,behavior:'instant'})}
function render(){const o=s.current,c=PAWN_CHARACTERS[o.character],it=E.item(o.itemId),known=o.status!=='offered',ev=E.event(s);$('coins').innerHTML=(s.coins<100000?fmt(s.coins):new Intl.NumberFormat('ko-KR',{notation:'compact',maximumFractionDigits:1}).format(s.coins))+'<span>G</span>';$('coins').setAttribute('aria-label',fmt(s.coins)+' 골드');$('coins').title=fmt(s.coins)+' G';$('day-label').textContent=s.day+'번째 밤';$('visitor-label').textContent='손님 '+s.visitor+' / 8';$('day-ticks').innerHTML=Array.from({length:8},(_,i)=>'<i class="'+(i<s.visitor-1?'past':i===s.visitor-1?'now':'')+'"></i>').join('');const lv=1+Math.floor(s.xp/120);$('shop-level').textContent='LV.'+lv+' '+(lv<4?'작은 가게':lv<9?'골목의 명소':'전설의 전당포');$('event-title').textContent=ev.title;$('event-short').textContent=ev.kind==='market'?(E.CATEGORIES[ev.category]||'모든 물건')+' 판매가 '+Math.round(((ev.mult||1)-1)*100)+'% 상승':ev.kind==='request'?(s.eventDone?'의뢰 완료':(E.CATEGORIES[ev.category]||'모든 품목')+' 수집 의뢰'):ev.kind==='gift'?'뜻밖의 손님이 남긴 선물':'진귀한 물건이 찾아오는 밤';$('stock-dot').hidden=!s.stock.length;
$('character').dataset.person=o.character;$('customer-name').textContent=c.name;$('customer-name').style.color=c.color;$('customer-role').textContent=c.role;$('customer-line').textContent=o.feedback||o.line||(s.met[o.character]>1?c.returnLine:c.greeting);$('visitor-tag').textContent=s.met[o.character]>1?'단골 · '+s.met[o.character]+'번째 방문':'처음 만나는 손님';$('scene-grade').textContent=known?E.GRADES[o.grade][0]+(o.genuine?' · 진품':' · 모조품'):'미감정 물품';$('scene-item').dataset.item=it.id;$('scene-item').dataset.grade=known?o.grade:1;$('lot-category').textContent=E.CATEGORIES[it.category]+' / LOT '+String(s.serial).padStart(3,'0');$('lot-name').textContent=it.name;$('lot-grade').className='grade-badge'+(known?'':' unknown');$('lot-grade').style.setProperty('--grade',known?E.GRADES[o.grade][1]:'#baaba0');$('lot-grade').textContent=known?E.GRADES[o.grade][0]:o.checks.length>=2?'추정 '+E.GRADES[o.claimedGrade][0]:'미감정';
$('offer-view').hidden=s.closing||o.status!=='offered';$('reveal-view').hidden=s.closing||o.status==='offered';$('closing-view').hidden=!s.closing;
if(s.closing){$('closing-view').innerHTML='<div class="closing"><div class="eyebrow">THE END OF A NIGHT</div><h3>'+s.day+'번째 밤, 마감</h3><p>불을 끄기 전에 장부를 한 번 펼쳐봅니다.<br>다음 밤에는 또 어떤 이야기가 찾아올까요?</p><dl><dt>오늘 매입</dt><dd>'+s.dayBought+'개</dd><dt>오늘 실현 이익</dt><dd>'+(s.dayProfit>=0?'+':'')+fmt(s.dayProfit)+'G</dd><dt>마감 보너스</dt><dd>+'+(70+s.day*15)+'G</dd></dl><button class="btn primary" data-action="next-day">정산하고 다음 밤으로</button></div>'}
else if(o.status==='offered'){for(const el of document.querySelectorAll('[data-inspect]')){el.disabled=false;el.classList.toggle('checked',o.checks.includes(el.dataset.inspect));el.setAttribute('aria-pressed',String(o.lastCheck===el.dataset.inspect))}$('clue-label').textContent='감정 노트 · '+o.checks.length+' / 3';$('clue-text').textContent=o.clues?.[o.lastCheck]||'도구가 알려주는 것은 단서뿐. 정교한 위조품은 감정을 통과할 수 있습니다.';const spread=Math.max(.25,(o.checks.length>=3?.38:.6)-s.upgrades.appraisal*.02);$('estimate-value').textContent=o.checks.length>=2?fmt(o.estimate*(1-spread))+' ~ '+fmt(o.estimate*(1+spread))+'G · 추정':'단서가 더 필요합니다';$('asking-label').textContent=o.price<o.asking?'흥정한 매입가':'손님의 요청가';$('asking-price').innerHTML=(o.price<o.asking?'<del>'+fmt(o.asking)+'</del>':'')+fmt(o.price)+'<small>G</small>';$('haggle-label').textContent='흥정 기회 '+Math.max(0,2-o.attempts)+'번';for(const el of document.querySelectorAll('[data-haggle]'))el.disabled=o.attempts>=2;$('buy-button').textContent=fmt(o.price)+'G에 매입';$('buy-button').disabled=s.coins<o.price||s.stock.length>=E.capacity(s);$('trade-help').textContent=s.coins<o.price?'소지금이 부족하면 보관함의 물건을 판매하세요.':s.stock.length>=E.capacity(s)?'보관함이 가득 찼어요. 물건 하나를 팔아 주세요.':'감정은 추정입니다. 매입하면 진짜 가치가 공개됩니다.'}
else{const lot=s.stock.find(x=>x.uid===o.uid),quick=lot?E.quote(s,lot):o.sale,display=lot?E.quote(s,lot,'display'):0,profit=quick-o.paid;let buttons;if(o.status==='sold')buttons='<button class="btn primary wide" data-action="next">다음 손님 맞이하기</button>';else if(lot?.displayAt!==null&&lot?.displayAt!==undefined)buttons='<div class="display-status wide">'+Math.max(0,lot.displayAt-s.turn)+'명 뒤 '+fmt(lot.displayPrice)+'G에 판매</div><button class="btn primary wide" data-action="next">다음 손님 맞이하기</button>';else buttons='<button class="btn primary" data-action="quick-sale" data-uid="'+o.uid+'">바로 판매 · '+fmt(quick)+'G</button><button class="btn secondary" data-action="display-sale" data-uid="'+o.uid+'">진열 · '+fmt(display)+'G</button><button class="btn secondary wide" data-action="next">보관하고 다음 손님</button>';
$('reveal-view').innerHTML='<div class="reveal" style="--grade:'+E.GRADES[o.grade][1]+'"><div class="eyebrow">'+(o.status==='sold'?'거래를 마쳤습니다':!o.genuine?'정교한 위조품에 당했습니다':o.value>o.paid*3?'숨은 보물을 발견했습니다':'물건의 진짜 얼굴')+'</div>'+badge(o.grade,o.genuine?E.GRADES[o.grade][0]+' · 진품':E.GRADES[o.grade][0]+' · 모조품')+'<div class="reveal-art">'+art(it.id,o.grade)+'</div><h3>'+esc(it.name)+'</h3><p>'+esc(o.genuine?it.effect:'겉모습은 완벽하지만, 숨겨진 힘은 없었습니다.')+'</p><div class="value-reveal"><small>'+(o.status==='sold'?'판매 완료':'실제 가치')+'</small>'+fmt(o.status==='sold'?o.sale:o.value)+' G</div><span class="profit-label '+(profit<0?'loss':'')+'">'+(o.status==='sold'?'실현 이익 ':'즉시 판매 시 ')+(profit>=0?'+':'')+fmt(profit)+'G</span><div class="reveal-buttons">'+buttons+'</div></div>'}
const displayed=s.stock.filter(x=>x.displayAt!==null);$('shelf-preview').innerHTML='<div><b>유리 진열장</b>'+(displayed.length?displayed.length+'개 판매를 기다리는 중':'두 손님이 다녀가면 더 좋은 값에 판매')+'</div>'+displayed.slice(0,3).map(x=>art(x.itemId,x.grade)).join('')+'<button data-action="stock">열기 ＋</button>';
if(view!=='trade'&&window.PawnPanels)window.PawnPanels.render(view);paintItems();paintPeople()}
function openDialog(html){$('dialog-body').innerHTML=html;if(!$('detail-dialog').open)$('detail-dialog').showModal();paintItems();paintPeople()}
function customerInfo(index=s.current.character){const c=PAWN_CHARACTERS[index],met=s.met[index]||0;openDialog(portrait(index,'person-art')+'<div class="eyebrow">'+esc(c.role)+'</div><h2 style="color:'+c.color+'">'+esc(c.name)+'</h2><p>“'+esc(met?c.secret:'아직 가게에 찾아오지 않은 손님입니다.')+'”</p><dl><dt>흥정 성향</dt><dd>'+esc(c.style)+'</dd><dt>원하는 물건</dt><dd>'+esc(met?c.request:'만나면 알 수 있어요.')+'</dd><dt>방문 횟수</dt><dd>'+met+'회</dd></dl>')}
function eventInfo(){const ev=E.event(s),character=Number.isInteger(ev.character)?ev.character:0;openDialog('<div class="eyebrow">'+s.day+'번째 밤의 사건</div><h2>'+esc(ev.title)+'</h2><p>'+esc(ev.description)+'</p>'+portrait(character,'person-art')+'<p>'+esc(s.eventDone?ev.resolveText:ev.requestText)+'</p><div class="display-status">'+(ev.kind==='market'?(E.CATEGORIES[ev.category]||'모든 품목')+' 판매가 ×'+ev.mult:ev.kind==='request'?(s.eventDone?'의뢰를 완료했습니다.':'조건에 맞는 진품을 보관함에서 전달하세요.'):ev.kind==='gift'?'보상은 금고에 지급되었습니다.':'희귀한 물건을 만날 가능성이 높아집니다.')+'</div><button class="btn primary" data-action="dialog-close">알겠어요</button>')}
function settings(){openDialog('<div class="eyebrow">AFTER HOURS</div><h2>잠깐 쉬어가도 괜찮아요</h2><p>시간 제한은 없습니다. 돌아오면 같은 손님과 이어서 거래할 수 있어요.</p><div class="settings-row"><span>수집과 거래 효과음</span><button data-action="sound">'+(s.sound?'켜짐':'꺼짐')+'</button></div><div class="settings-row"><span>진행 상황</span><button data-action="save">지금 저장</button></div><p class="save-note">'+(saveOK?'이 기기·브라우저에 자동 저장됩니다.':'현재 브라우저에서 저장할 수 없습니다.')+' 다른 기기와는 동기화되지 않습니다.</p><p class="save-note">도움말: 감정 도구는 불확실한 단서를 제공합니다. 정교한 가품은 검사를 통과하고, 진품도 수상해 보일 수 있습니다. 실제 가치는 매입 후 공개됩니다. 흥정 후 매입하고, 즉시 판매하거나 두 손님 뒤에 팔리는 진열 판매를 고르세요.</p><button class="btn secondary danger" data-action="reset-ask">새 가게 시작하기</button>')}
function action(name,target){const uid=target?.dataset.uid;if(name==='next'){run(E.next);window.scrollTo({top:0,behavior:'instant'})}else if(name==='next-day'){run(E.nextDay);window.scrollTo({top:0,behavior:'instant'})}else if(name==='quick-sale')run(E.sell,uid,'quick');else if(name==='display-sale')run(E.sell,uid,'display');else if(name==='deliver'){const result=run(E.sell,uid,'request');if(result.ok)toast(E.event(s).resolveText)}else if(name==='stock')switchView('stock');else if(name==='dialog-close')$('detail-dialog').close();else if(name==='sound'){s.sound=!s.sound;save();settings();tone('coin')}else if(name==='save'){save();toast(saveOK?'이 기기에 저장했어요.':'저장할 수 없습니다.')}else if(name==='reset-ask')openDialog('<h2>새 가게를 시작할까요?</h2><p>현재 금고, 수집록, 거래 기록이 모두 초기화됩니다.</p><button class="btn danger" data-action="reset-confirm">기록을 지우고 처음부터</button><button class="btn secondary" data-action="dialog-close">취소</button>');else if(name==='reset-confirm'){s=E.create();save();$('detail-dialog').close();switchView('trade');toast('새로운 밤이 시작됐어요.') }else if(window.PawnPanels)window.PawnPanels.action(name,target)}
document.addEventListener('click',e=>{const el=e.target.closest('button');if(!el||el.disabled)return;if(el.dataset.action)action(el.dataset.action,el);if(el.dataset.inspect){if(s.current.checks.includes(el.dataset.inspect)){s.current.lastCheck=el.dataset.inspect;render();save()}else run(E.check,el.dataset.inspect);if(innerWidth<=760)requestAnimationFrame(()=>{const note=$('clue-box'),r=note.getBoundingClientRect(),bar=document.querySelector('.deal-actions'),fixed=getComputedStyle(bar).position==='fixed',limit=fixed?bar.getBoundingClientRect().top:innerHeight-parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--nav-height'));if(r.bottom>limit-12||r.top<12)note.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})});}if(el.dataset.haggle)run(E.negotiate,Number(el.dataset.haggle));if(el.dataset.view)switchView(el.dataset.view);if(el.dataset.stockFilter){stockFilter=el.dataset.stockFilter;render()}if(el.dataset.codexMode){codexMode=el.dataset.codexMode;render()}if(el.dataset.category){category=el.dataset.category;render()}});
$('buy-button').onclick=()=>run(E.buy);$('pass-button').onclick=()=>{run(E.next);window.scrollTo({top:0,behavior:'instant'})};$('event-banner').onclick=eventInfo;$('customer-info').onclick=()=>customerInfo();$('settings-button').onclick=settings;$('close-dialog').onclick=()=>$('detail-dialog').close();$('aid-button').onclick=()=>run(E.aid);$('detail-dialog').addEventListener('click',e=>{if(e.target===$('detail-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});window.addEventListener('pagehide',save);document.addEventListener('visibilitychange',()=>{if(document.hidden)save()});
window.PawnApp={get state(){return s},get stockFilter(){return stockFilter},get codexMode(){return codexMode},get category(){return category},E,esc,fmt,art,portrait,badge,run,render,openDialog,customerInfo,switchView,toast,save};
render();save();
function fitControls(){const nav=document.querySelector('.bottom-nav').getBoundingClientRect().height,deal=document.querySelector('.deal-actions').getBoundingClientRect().height;document.documentElement.style.setProperty('--nav-height',nav+'px');if(deal)document.documentElement.style.setProperty('--deal-height',deal+'px')}
fitControls();if(window.ResizeObserver){const controls=new ResizeObserver(fitControls);controls.observe(document.querySelector('.bottom-nav'));controls.observe(document.querySelector('.deal-actions'))}window.addEventListener('resize',fitControls);
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'read_pawnshop',title:'전당포 상태 읽기',description:'현재 전당포의 금고, 날짜, 재고, 수집 현황과 감정한 단서를 조회합니다. 게임 상태를 바꾸지 않습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(input!==undefined&&(input===null||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length))throw new Error('빈 객체가 필요합니다.');const o=s.current;return{coins:s.coins,day:s.day,visitor:s.visitor,collected:Object.keys(s.discovered).length,met:Object.keys(s.met).length,stock:s.stock.length,current:{item:E.item(o.itemId).name,status:o.status,asking:o.price,checks:o.checks,...(o.status!=='offered'?{grade:E.GRADES[o.grade][0],genuine:o.genuine,value:o.value}:{})}}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}
})();
