'use strict';
(function(G){
const GRADES=[['낡음','#8f929e',.55],['평범','#c9c2b8',1],['양질','#84c995',1.6],['희귀','#77bbed',2.6],['진귀','#bd91e8',4.2],['유물','#eaa76b',7],['전설','#efce68',12],['신화','#ee8cac',21],['금기','#eb686d',38]];
const CATEGORIES={clock:'시계',jewelry:'장신구',weapon:'무기',book:'고서',potion:'물약',relic:'유물',music:'악기',tool:'도구',mask:'가면',toy:'장난감',art:'미술품',cosmic:'별의 물건'};
const CONDITIONS=[['낡았지만 온전함',.72],['세월의 흔적',.88],['좋은 상태',1],['거의 새것',1.15],['완벽한 보존',1.3]];
const UPGRADE_COSTS=[250,650,1600,3500,7500];
const ACHIEVEMENTS=[{id:'first',name:'첫 번째 거래',text:'물건 1개 매입',key:'bought',goal:1,reward:60},{id:'profit',name:'보는 눈이 있군요',text:'누적 이익 500G',key:'profit',goal:500,reward:100},{id:'ten',name:'단골이 생겼어요',text:'물건 10개 매입',key:'bought',goal:10,reward:180},{id:'twelve',name:'작은 박물관',text:'서로 다른 물건 12종 발견',key:'discovery',goal:12,reward:220},{id:'rare',name:'밤의 감정사',text:'희귀 이상 5개 매입',key:'rare',goal:5,reward:300},{id:'book',name:'백과사전의 첫 장',text:'서로 다른 물건 36종 발견',key:'discovery',goal:36,reward:600},{id:'legend',name:'전설과 악수하다',text:'전설 이상 1개 매입',key:'legend',goal:1,reward:900},{id:'master',name:'백야의 전당포',text:'누적 이익 30,000G',key:'profit',goal:30000,reward:1500}];
const items=()=>G.PAWN_ITEMS||[];const chars=()=>G.PAWN_CHARACTERS||[];const events=()=>G.PAWN_EVENTS||[];
function rand(s){s.seed=(Math.imul(s.seed,1664525)+1013904223)>>>0;return s.seed/4294967296}
function pick(s,a){return a[Math.floor(rand(s)*a.length)]}
function item(id){return items().find(x=>x.id===id)||items()[0]}
function event(s){if(s.activeEvent?.day===s.day)return s.activeEvent;return events()[((s.day-1)*7)%Math.max(1,events().length)]||{title:'조용한 밤',description:'골목 끝 전당포에 불이 켜졌습니다.',kind:'market',category:'clock',mult:1.2,gift:0}}
function log(s,text,type='normal'){s.log.unshift({day:s.day,text,type});s.log=s.log.slice(0,40)}
function notify(s,text){s.notices.push(text);s.notices=s.notices.slice(-8)}
function baseState(){return{version:3,seed:(Date.now()^Math.floor(Math.random()*1e9))>>>0,coins:650,day:1,visitor:1,turn:0,serial:0,xp:0,bought:0,sold:0,profit:0,rare:0,legend:0,stock:[],discovered:{},met:{},claimed:[],upgrades:{appraisal:0,shelves:0,word:0},log:[],notices:[],current:null,closing:false,dayStart:650,dayBought:0,dayProfit:0,eventDone:false,aidDay:0,sound:false}}
function create(){const s=baseState();log(s,'오래된 열쇠를 받았다. 오늘부터 이 가게의 주인이다.');roll(s,true);return s}
function tier(s){const weights=[9,24,27,21,11,5.5,1.8,.6,.1];const boost=Math.min(3,s.upgrades.word*.3+s.day*.035)+(event(s).kind==='rumor'?(event(s).mult||1.3)-.7:0);let r=rand(s)*100,total=0,g=1;for(let i=0;i<weights.length;i++){total+=weights[i];if(r<total){g=i;break}}if(rand(s)<boost*.23)g=Math.min(8,g+1);if(s.visitor===8)g=Math.max(3,g);return g}
function signals(s,o){if(o.signals)return;o.signals=[rand(s),rand(s),rand(s)];o.claimedGrade=o.claimedGrade??o.grade;o.apparent=o.apparent??Math.round(o.genuine?o.value:o.value/.13);o.estimate=Math.max(8,Math.round(o.apparent*(.86+rand(s)*.28)));o.clues=o.clues||{};o.lastCheck=o.checks.at(-1)||null;}
function roll(s,first=false){const data=first?(items().find(x=>x.id==='clock-01')||items()[0]):pick(s,items());const character=first?0:Math.floor(rand(s)*chars().length),claimedGrade=first?2:tier(s),condition=first?3:Math.floor(rand(s)*5);const risk=[1,19,23,7].includes(character)?.31:[6,7,12,20].includes(character)?.15:.22;const genuine=first||rand(s)>=risk;const sleeper=genuine&&(first||rand(s)<.12);const grade=first?4:sleeper?Math.min(8,claimedGrade+2+Math.floor(rand(s)*2)):claimedGrade;const apparent=Math.round(data.base*GRADES[claimedGrade][2]*CONDITIONS[condition][1]);const value=first?680:Math.max(5,Math.round(genuine?data.base*GRADES[grade][2]*CONDITIONS[condition][1]:apparent*(.055+rand(s)*.16)));const asking=first?120:Math.max(12,Math.round(apparent*(.58+rand(s)*.54)));s.met[character]=(s.met[character]||0)+1;s.serial++;s.current={uid:'lot-'+s.serial,itemId:data.id,grade,claimedGrade,condition,genuine,sleeper,apparent,value,asking,price:asking,floor:Math.round(asking*(([1,9,23].includes(character)?.8:[0,4,8,14].includes(character)?.62:.68)+rand(s)*.13-Math.min(.08,s.upgrades.word*.012)-Math.min(.045,((s.met[character]||1)-1)*.005))),character,checks:[],attempts:0,status:'offered',line:first?'야옹. 이 시계, 자정에는 거꾸로 가요. 120G면 데려가실래요?':null,wasFirst:first,feedback:'',negotiated:false,sale:0,paid:0};signals(s,s.current);if(s.upgrades.appraisal>=4)check(s,'lens');if(s.upgrades.appraisal>=5){check(s,'lamp');check(s,'story')}}
function prepare(s){signals(s,s.current);if(s.current.line)s.current.line=s.current.line.replace(/^喵。?/, '야옹.');s.storyQueue=s.storyQueue||[];if(s.current.status==='offered'&&s.current.checks.length&&!Object.keys(s.current.clues).length){const old=[...s.current.checks];s.current.checks=[];for(const method of old)check(s,method)}return s;}
function capacity(s){return 8+s.upgrades.shelves*4}
function displayCapacity(s){return 3+s.upgrades.shelves}
function quote(s,lot,mode='quick'){const it=item(lot.itemId),ev=event(s),market=ev.kind==='market'&&(ev.category==='all'||ev.category===it.category)?ev.mult:1;return Math.round(lot.value*(mode==='display'?1.08:.85)*(1+s.upgrades.word*.035)*market)}
function check(s,method){const o=s.current;if(s.closing||!o||o.status!=='offered')return{ok:false,message:'감정할 물건이 없습니다.'};if(!['lens','lamp','story'].includes(method))return{ok:false,message:'알 수 없는 감정 도구입니다.'};if(o.checks.includes(method))return{ok:false,message:'이미 확인한 단서입니다.'};signals(s,o);const methods=[method];if(s.upgrades.appraisal>=1&&o.checks.length===0){const other=['lens','lamp','story'].find(x=>x!==method);methods.push(other)}if(s.upgrades.appraisal>=3)methods.push(...['lens','lamp','story']);const it=item(o.itemId),accuracy=Math.min(.88,.55+s.upgrades.appraisal*.055);for(const m of new Set(methods)){if(o.checks.includes(m))continue;o.checks.push(m);const ix=['lens','lamp','story'].indexOf(m),suspicious=o.genuine?o.signals[ix]<.13:o.signals[ix]<accuracy;let message;if(m==='lens')message=CONDITIONS[o.condition][0]+'. '+(suspicious?'모서리와 안쪽의 마모가 다릅니다. 수리 흔적일 수도, 오래된 척한 흔적일 수도 있습니다.':it.clue+' 세월의 흔적은 자연스러워 보입니다.');else if(m==='lamp')message=suspicious?'빛 아래 각인의 일부가 번집니다. 후대의 보수인지 복제 흔적인지는 단정하기 어렵습니다.':o.sleeper&&o.signals[1]<.55?'겉과 달리 내부에서 복잡한 빛의 무늬가 나타납니다. 낯선 제작 기법입니다.':'재료의 반응은 그럴듯합니다. 다만 정교한 모조품도 이 검사를 통과할 수 있습니다.';else message=it.story+(suspicious?' 하지만 제작 연대와 손님의 설명에 어긋나는 부분이 있습니다.':' 이야기는 앞뒤가 맞습니다. 증빙 서류는 없습니다.');o.clues[m]=message;o.lastCheck=m;}o.feedback='';return{ok:true,message:'단서를 기록했어요. 진위는 아직 확정할 수 없습니다.'}}
function negotiate(s,factor){const o=s.current;if(s.closing||!o||o.status!=='offered')return{ok:false,message:'진행 중인 거래가 없습니다.'};if(o.attempts>=2)return{ok:false,message:'흥정은 두 번까지 할 수 있어요.'};if(![.7,.85].includes(factor))return{ok:false,message:'올바른 제안을 골라 주세요.'};o.attempts++;const proposed=Math.round(o.asking*factor),c=chars()[o.character];if(proposed>=o.floor||o.wasFirst){o.price=Math.min(o.price,proposed);o.negotiated=true;o.feedback=c?.good||'좋아요. 그 가격으로 하죠.';return{ok:true,message:o.feedback}}o.price=Math.min(o.price,Math.round(o.asking*.94));o.feedback=(c?.bad||'그 가격은 어렵군요.')+' '+o.price+'G까지는 해 드리죠.';return{ok:true,message:o.feedback}}
function achievements(s){for(const a of ACHIEVEMENTS){const value=a.key==='discovery'?Object.keys(s.discovered).length:s[a.key];if(value>=a.goal&&!s.claimed.includes(a.id)){s.claimed.push(a.id);s.coins+=a.reward;notify(s,'업적 · '+a.name+' +'+a.reward+'G');log(s,a.name+' 달성. 보상 '+a.reward+'G.','good')}}}
function buy(s){const o=s.current;if(s.closing||!o||o.status!=='offered')return{ok:false,message:'이미 처리된 거래입니다.'};if(s.coins<o.price)return{ok:false,message:'소지금이 부족해요. 보관함의 물건을 팔거나 손님을 보내세요.'};if(s.stock.length>=capacity(s))return{ok:false,message:'보관함이 가득 찼어요. 물건 하나를 팔아 자리를 비워 주세요.'};s.coins-=o.price;o.paid=o.price;o.status='bought';const lot={uid:o.uid,itemId:o.itemId,grade:o.grade,condition:o.condition,genuine:o.genuine,value:o.value,paid:o.price,displayAt:null};s.stock.push(lot);s.storyQueue=s.storyQueue||[];if(o.wasFirst&&!s.storyQueue.some(x=>x.id==='clock-return'))s.storyQueue.push({id:'clock-return',day:s.day+2,title:'모카가 잃어버린 일 분',description:'고양이 상인이 다시 문을 밀었습니다. 그날의 시계 덕분에 놓친 마지막 인사를 되찾았다며, 작은 봉투를 남깁니다.',kind:'gift',category:'clock',mult:1.2,gift:140,character:0,requestText:'그때 시계, 기억해요? 잃어버린 시간은 돈으로 살 수 없다고 생각했는데요.',resolveText:'봉투에는 감사 편지와 140G가 들어 있었습니다.'});s.bought++;s.dayBought++;s.xp+=12+o.grade*3;if(o.grade>=3)s.rare++;if(o.grade>=6)s.legend++;const prev=s.discovered[o.itemId];s.discovered[o.itemId]={grade:Math.max(prev?.grade||0,o.grade),count:(prev?.count||0)+1,genuine:(prev?.genuine||false)||o.genuine};log(s,item(o.itemId).name+' 매입 −'+o.price+'G',o.genuine?'normal':'warn');achievements(s);return{ok:true,message:o.genuine?'숨겨진 가치를 발견했어요.':'정교한 모조품이었어요. 도감에 기록했습니다.',lot}}
function sell(s,uid,mode='quick'){const ix=s.stock.findIndex(x=>x.uid===uid);if(ix<0)return{ok:false,message:'이미 판매한 물건입니다.'};const lot=s.stock[ix];if(lot.displayAt!==null&&mode!=='complete')return{ok:false,message:'진열 판매를 기다리는 물건입니다.'};if(mode==='display'){if(s.stock.filter(x=>x.displayAt!==null).length>=displayCapacity(s))return{ok:false,message:'진열대가 가득 찼어요.'};lot.displayAt=s.turn+2;lot.displayPrice=quote(s,lot,'display');log(s,item(lot.itemId).name+' 진열. 손님 2명 뒤 판매됩니다.');return{ok:true,message:'손님 2명이 다녀가면 '+lot.displayPrice+'G에 판매돼요.'}}
if(!['quick','complete','request'].includes(mode))return{ok:false,message:'알 수 없는 판매 방식입니다.'};if(mode==='complete'&&(lot.displayAt===null||lot.displayAt>s.turn))return{ok:false,message:'아직 판매 시점이 아닙니다.'};const ev=event(s);if(mode==='request'&&(s.eventDone||ev.kind!=='request'||!lot.genuine||(ev.category!=='all'&&ev.category!==item(lot.itemId).category)))return{ok:false,message:'의뢰 조건에 맞지 않습니다.'};const amount=mode==='complete'?lot.displayPrice:mode==='request'?Math.round(lot.value*(ev.mult||1.4))+(ev.gift||0):quote(s,lot);if(mode==='request'){s.eventDone=true;s.xp+=35}const profit=amount-lot.paid;s.coins+=amount;s.profit+=profit;s.dayProfit+=profit;s.sold++;s.xp+=8;s.stock.splice(ix,1);if(s.current?.uid===uid){s.current.status='sold';s.current.sale=amount}s.log.unshift({day:s.day,text:item(lot.itemId).name+' 판매 +'+amount+'G (이익 '+(profit>=0?'+':'')+profit+'G)',type:profit>=0?'good':'warn'});s.log=s.log.slice(0,40);if(mode==='complete')notify(s,'진열 판매 완료 · '+item(lot.itemId).name+' +'+amount+'G');achievements(s);return{ok:true,message:'판매 완료. '+(profit>=0?'+':'')+profit+'G 이익',amount,profit}}
function next(s){if(s.closing)return{ok:false,message:'영업을 마감해 주세요.'};s.turn++;for(const lot of [...s.stock])if(lot.displayAt!==null&&lot.displayAt<=s.turn)sell(s,lot.uid,'complete');if(s.visitor>=8){s.closing=true;return{ok:true,closing:true}}s.visitor++;roll(s);return{ok:true}}
function nextDay(s){if(!s.closing)return{ok:false,message:'아직 영업 중입니다.'};const bonus=70+s.day*15;s.coins+=bonus;s.day++;s.visitor=1;s.dayStart=s.coins;s.dayBought=0;s.dayProfit=0;s.closing=false;s.eventDone=false;s.xp+=15;log(s,'하루 정산 보너스 +'+bonus+'G. 새로운 밤이 시작됩니다.','good');s.activeEvent=(s.storyQueue||[]).find(x=>x.day===s.day)||null;const ev=event(s);if(ev.kind==='gift'){s.coins+=Math.max(0,ev.gift||80);notify(s,ev.title+' +'+Math.max(0,ev.gift||80)+'G');s.eventDone=true}roll(s);return{ok:true,message:'정산 보너스 +'+bonus+'G'}}
function upgrade(s,key){if(!Object.hasOwn(s.upgrades,key))return{ok:false,message:'알 수 없는 강화입니다.'};const level=s.upgrades[key],cost=UPGRADE_COSTS[level];if(cost===undefined)return{ok:false,message:'최고 단계입니다.'};if(s.coins<cost)return{ok:false,message:'소지금이 부족합니다.'};s.coins-=cost;s.upgrades[key]++;log(s,({appraisal:'감정 도구',shelves:'보관함',word:'가게 평판'})[key]+' 강화 −'+cost+'G','good');return{ok:true,message:'가게가 한 단계 성장했어요.'}}
function aid(s){if(s.coins>=120||s.stock.length||s.aidDay===s.day)return{ok:false,message:'소지금 120G 미만, 재고가 없을 때 하루 한 번 받을 수 있어요.'};s.coins+=200;s.aidDay=s.day;log(s,'옆집 약손의 심부름을 마쳤다. +200G','good');return{ok:true,message:'약손의 심부름 보상 +200G'}}
function validate(s){const finite=v=>Number.isFinite(v)&&Math.abs(v)<1e13;const integer=v=>Number.isInteger(v)&&v>=0;const validItem=id=>items().some(x=>x.id===id);if(!s||s.version!==3||!finite(s.coins)||s.coins<0||!Array.isArray(s.stock)||!s.current)return false;if(!s.upgrades||!s.discovered||!s.met||!Array.isArray(s.claimed)||!Array.isArray(s.log)||!Array.isArray(s.notices))return false;if(!Number.isInteger(s.day)||s.day<1||!Number.isInteger(s.visitor)||s.visitor<1||s.visitor>8)return false;for(const k of ['appraisal','shelves','word'])if(!integer(s.upgrades[k])||s.upgrades[k]>5)return false;for(const k of ['seed','turn','serial','xp','bought','sold','rare','legend','dayBought','aidDay'])if(!integer(s[k]))return false;for(const k of ['profit','dayProfit','dayStart'])if(!finite(s[k]))return false;const o=s.current;if(!validItem(o.itemId)||!['offered','bought','sold'].includes(o.status)||!Array.isArray(o.checks)||o.checks.some(x=>!['lens','lamp','story'].includes(x))||!integer(o.grade)||o.grade>8||!integer(o.character)||o.character>=chars().length||!integer(o.attempts)||o.attempts>2||typeof o.genuine!=='boolean')return false;for(const k of ['value','asking','price','floor','paid','sale'])if(!finite(o[k])||o[k]<0)return false;if(typeof o.uid!=='string'||!integer(o.condition)||o.condition>4)return false;for(const [id,d] of Object.entries(s.discovered))if(!validItem(id)||!d||!integer(d.grade)||d.grade>8||!integer(d.count)||typeof d.genuine!=='boolean')return false;for(const [id,n] of Object.entries(s.met))if(!/^\d+$/.test(id)||Number(id)>=chars().length||!integer(n))return false;const ids=new Set();for(const lot of s.stock){if(!validItem(lot.itemId)||ids.has(lot.uid)||!finite(lot.value)||lot.value<0||!finite(lot.paid)||lot.paid<0||!integer(lot.grade)||lot.grade>8||typeof lot.genuine!=='boolean')return false;ids.add(lot.uid);if(lot.displayAt!==null&&(!integer(lot.displayAt)||!finite(lot.displayPrice)||lot.displayPrice<0))return false}return true}
G.PawnEngine={GRADES,CATEGORIES,CONDITIONS,UPGRADE_COSTS,ACHIEVEMENTS,create,validate,prepare,item,event,capacity,displayCapacity,quote,check,negotiate,buy,sell,next,nextDay,upgrade,aid,achievements};
})(globalThis);
