'use strict';
(function(G){
const GRADES=[['낡음','#8f929e',.55],['평범','#c9c2b8',1],['양질','#84c995',1.6],['희귀','#77bbed',2.6],['진귀','#bd91e8',4.2],['유물','#eaa76b',7],['전설','#efce68',12],['신화','#ee8cac',21],['금기','#eb686d',38]];
const CATEGORIES={clock:'시계',jewelry:'장신구',weapon:'무기',book:'고서',potion:'물약',relic:'유물',music:'악기',tool:'도구',mask:'가면',toy:'장난감',art:'미술품',cosmic:'별의 물건'};
const CONDITIONS=[['손상·수리 흔적',.72],['마모와 손상',.88],['좋은 상태',1],['거의 새것',1.15],['완벽한 보존',1.3]];
const UPGRADE_COSTS=[250,650,1600,3500,7500];
const ACHIEVEMENTS=[{id:'first',name:'첫 번째 거래',text:'물건 1개 매입',key:'bought',goal:1,reward:60},{id:'profit',name:'보는 눈이 있군요',text:'누적 이익 500G',key:'profit',goal:500,reward:100},{id:'ten',name:'단골이 생겼어요',text:'물건 10개 매입',key:'bought',goal:10,reward:180},{id:'twelve',name:'작은 박물관',text:'서로 다른 물건 12종 발견',key:'discovery',goal:12,reward:220},{id:'rare',name:'밤의 감정사',text:'희귀 이상 5개 매입',key:'rare',goal:5,reward:300},{id:'book',name:'백과사전의 첫 장',text:'서로 다른 물건 36종 발견',key:'discovery',goal:36,reward:600},{id:'legend',name:'전설과 악수하다',text:'전설 이상 1개 매입',key:'legend',goal:1,reward:900},{id:'master',name:'백야의 전당포',text:'누적 이익 30,000G',key:'profit',goal:30000,reward:1500}];
const items=()=>G.PAWN_ITEMS||[],chars=()=>G.PAWN_CHARACTERS||[],events=()=>G.PAWN_EVENTS||[];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),clone=x=>JSON.parse(JSON.stringify(x)),MAX_OFFER=999999999;
const INVESTIGATION_OPTIONS=[{id:'lens-mark',label:'각인·표식',tool:'lens',hint:'돋보기로 작은 선과 문자를 살펴봅니다.'},{id:'lens-material',label:'재료·빛깔',tool:'lens',hint:'돋보기로 표면과 단면을 살펴봅니다.'},{id:'lens-wear',label:'마모·접합',tool:'lens',hint:'돋보기로 모서리와 이음새를 살펴봅니다.'},{id:'light-mark',label:'각인·표식',tool:'light',hint:'불빛을 비추며 표식의 색과 반사를 봅니다.'},{id:'light-material',label:'재료·빛깔',tool:'light',hint:'불빛 아래 재료의 빛깔을 살펴봅니다.'},{id:'light-wear',label:'마모·접합',tool:'light',hint:'불빛을 움직이며 모서리와 이음새를 봅니다.'}];
const validItem=id=>items().some(x=>x.id===id),integer=v=>Number.isSafeInteger(v)&&v>=0,finite=v=>Number.isFinite(v)&&Math.abs(v)<1e13;
function rand(s){s.seed=(Math.imul(s.seed,1664525)+1013904223)>>>0;return s.seed/4294967296}
function pick(s,a){return a[Math.floor(rand(s)*a.length)]}
function item(id){return items().find(x=>x.id===id)||items()[0]}
function profile(index){const p=G.PAWN_PROFILES?.[index]||{};return{likes:[],dislikes:[],temperament:'practical',patience:4,expertise:.5,honesty:.72,frugality:.5,interest:'물건에 남은 이야기',manner:'차분하게 값을 비교합니다.',lines:{},...p,patience:clamp(Math.round(p.patience||4),3,6),expertise:clamp(p.expertise??.5,0,1),honesty:clamp(p.honesty??.72,0,1),frugality:clamp(p.frugality??.5,0,1)}}
function relationship(s,index){return clamp(Number(s.relationships?.[index])||0,-100,100)}
function relationLabel(n){return n>=65?'믿음직한 단골':n>=25?'가까워지는 사이':n<=-65?'돌아서기 직전':n<=-25?'불편한 사이':'서로 알아가는 중'}
function event(s){return s.activeEvent||{id:'quiet',day:s.day,title:'조용한 밤',description:'골목 끝 전당포에 불이 켜졌습니다.',kind:'market',category:'all',mult:1.15,gift:0}}
function log(s,text,type='normal'){s.log.unshift({day:s.day,text,type});s.log=s.log.slice(0,40)}
function notify(s,text){s.notices.push(text);s.notices=s.notices.slice(-8)}
function history(o,speaker,text){o.history.push({speaker,text});if(speaker==='customer')o.feedback=text}
function note(o,text){if(!o.notes.includes(text))o.notes.push(text);o.notes=o.notes.slice(-12);history(o,'note',text)}
function changeRelation(s,delta,reason){const o=s.current,old=relationship(s,o.character),next=clamp(old+delta,-100,100);s.relationships[o.character]=next;o.relationDelta+=(next-old);if(next!==old)history(o,'note','친밀도 '+(next>old?'+':'')+(next-old)+' · '+reason)}
function line(s,key,fallback){const o=s.current,p=profile(o.character),list=p.lines?.[key];const text=Array.isArray(list)&&list.length?pick(s,list):fallback;return String(text||'').replace(/\{item\}/g,item(o.itemId).name).replace(/\{price\}/g,Math.round(o.price).toLocaleString('ko-KR')).replace(/\{category\}/g,CATEGORIES[item(o.itemId).category]||'물건')}
function baseState(seed){return{version:5,seed:Number.isInteger(seed)?seed>>>0:(Date.now()^Math.floor(Math.random()*1e9))>>>0,coins:650,day:1,visitor:1,turn:0,serial:0,xp:0,bought:0,sold:0,profit:0,rare:0,legend:0,stock:[],discovered:{},met:{},relationships:{},claimed:[],upgrades:{appraisal:0,shelves:0,word:0},log:[],notices:[],current:null,closing:false,dayStart:650,dayBought:0,dayProfit:0,eventDone:false,aidDay:0,sound:false,activeEvent:null,lastEventId:null,lastCharacter:null,lastItemId:null}}
function selectEvent(s,payGift=true){const available=events().filter(x=>x.id!==s.lastEventId),ev=pick(s,available.length?available:events());s.activeEvent=ev?{...clone(ev),day:s.day}:null;s.lastEventId=ev?.id||null;s.eventDone=false;if(payGift&&event(s).kind==='gift'){const amount=Math.max(0,event(s).gift||0);s.coins+=amount;s.eventDone=true;notify(s,event(s).title+' +'+amount+'G');log(s,'오늘의 선물 +'+amount+'G','good')}}
function create(seed){const s=baseState(seed);log(s,'오래된 열쇠를 받았다. 오늘부터 이 가게의 주인이다.');selectEvent(s);roll(s);return s}
function tier(s){const weights=[9,24,27,21,11,5.5,1.8,.6,.1];let r=rand(s)*100,g=8;for(let i=0;i<weights.length;i++){r-=weights[i];if(r<0){g=i;break}}const boost=Math.min(.5,s.upgrades.word*.045+s.day*.006)+(event(s).kind==='rumor'?((event(s).mult||1.3)-1)*.4:0);if(rand(s)<boost)g=Math.min(8,g+1);return g}
function capacity(s){return 8+s.upgrades.shelves*4}
function displayCapacity(s){return 3+s.upgrades.shelves}
function quote(s,lot,mode='quick'){const it=item(lot.itemId),ev=event(s),market=ev.kind==='market'&&(ev.category==='all'||ev.category===it.category)?ev.mult:1;return Math.round(lot.value*(mode==='display'?1.08:.85)*(1+s.upgrades.word*.035)*market)}
function marketFactor(s,it){const ev=event(s);return ev.kind==='market'&&(ev.category==='all'||ev.category===it.category)?ev.mult:1}
const AXES=['authenticity','quality','condition'],AXIS_TITLES={authenticity:'제작 출처 · 진위',quality:'제작 솜씨 · 세공',condition:'보존 상태 · 손상'};
const qualityBand=g=>g<=1?0:g<=4?1:2,conditionBand=c=>c<=1?0:c<=3?1:2;
function stable(o,salt){let h=2166136261;for(const ch of o.uid+':'+o.itemId+':'+o.character+':'+salt){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0)/4294967296}
function catalogFor(o){const b=G.PAWN_APPRAISAL_CATALOG[item(o.itemId).category],v=G.PAWN_APPRAISAL_OVERRIDES?.[o.itemId]||{};return Object.fromEntries(Object.entries(b).map(([k,x])=>[k,{...x,...(v[k]||{})}]))}
function voice(s,key,data={}){const o=s.current,p=profile(o.character);return G.PawnVoice.say(o.character,key,{item:item(o.itemId).name,price:o.price,category:CATEGORIES[item(o.itemId).category],likes:p.likes.map(k=>CATEGORIES[k]).join(', '),interest:p.interest,...data})}
function buildInvestigations(s,o){
 if(o.investigationVersion===2&&o.investigations&&o.evidence?.axes)return;
 const c=catalogFor(o),axes={};
 for(const key of AXES){const spec=c[key],actual=key==='authenticity'?Number(o.genuine):key==='quality'?qualityBand(o.grade):conditionBand(o.condition);let claimed=key==='authenticity'?1:key==='quality'?qualityBand(o.claimedGrade??o.grade):actual;
 if(o.intent==='fraud'&&key==='condition'&&actual<2)claimed=2;
 if(o.intent==='fraud'&&o.genuine&&key==='quality'&&actual<2)claimed=2;
 const full=key==='authenticity'?(o.genuine?spec.observedGenuine:spec.observedReplica):spec.observations[actual],claim=key==='authenticity'?(claimed?spec.claimGenuine:spec.claimReplica):spec.claims[claimed];
 let requiredLevel=0;if(key==='authenticity')requiredLevel=Number.isInteger(o.appraisalClarity)?clamp(o.appraisalClarity,0,5):((o.condition<=1&&stable(o,'wear')<.38)||(!o.genuine&&o.grade>=3&&stable(o,'copy')<.28))?1+Math.floor(stable(o,'clarity')*5):0;
 axes[key]={key,tool:spec.tool,site:spec.site,reference:spec.reference,claim,actual,claimed,full,unclear:spec.observedUnclear||'',requiredLevel,observedActual:false};}
 o.evidence={...(o.evidence||{}),axes,physical:o.evidence?.physical??0};o.investigationVersion=2;o.inspectionLeft=6;o.inspected=[];o.inspectionResults={};o.inspectionLevels={};o.investigations={};o.lastInspection=null;
 for(const opt of INVESTIGATION_OPTIONS){const a=Object.values(axes).find(a=>a.tool+'-'+a.site===opt.id);o.investigations[opt.id]=a?a.full:opt.tool==='lens'?c.sites[opt.id.split('-')[1]].label+'의 윤곽은 보인다. 색 변화와 빛의 반사 양상은 확대만으로 확인되지 않는다.':c.sites[opt.id.split('-')[1]].label+'에 밝은 부분과 그림자가 생긴다. 작은 홈이나 미세한 선까지는 맨눈으로 읽히지 않는다.'}
}
function investigationOptions(s){if(!openTrade(s)||s.current.kind!=='seller')return[];const c=catalogFor(s.current);return INVESTIGATION_OPTIONS.map(x=>({...x,label:c.sites[x.id.split('-')[1]].label,hint:x.tool==='lens'?'작은 홈·선·표면을 확대':'빛깔·반사·투과를 관찰'}))}
function investigationCost(){return 0}
function investigate(s,id){const o=s.current,opt=investigationOptions(s).find(x=>x.id===id);if(!opt)return{ok:false,message:'지금 조사할 수 없는 곳입니다.'};const a=Object.values(o.evidence.axes).find(a=>a.tool+'-'+a.site===id),clear=!a||s.upgrades.appraisal>=a.requiredLevel,observation=a?(clear?a.full:a.unclear):o.investigations[id];if(o.inspectionResults[id]===observation)return{ok:true,message:observation,observation,id,cost:0,repeated:true};o.relationDelta=0;if(!o.inspected.includes(id))o.inspected.push(id);o.inspectionLeft=6-o.inspected.length;o.physicalUsed=true;if(!o.checks.includes(id))o.checks.push(id);o.inspectionResults[id]=observation;o.inspectionLevels[id]=s.upgrades.appraisal;o.lastInspection=id;if(a)a.observedActual=clear;history(o,'player',(opt.tool==='lens'?'돋보기':'불빛')+' · '+opt.label);note(o,observation);return{ok:true,message:observation,observation,id,cost:0}}
function appraisalNotebook(s){const o=s.current,c=catalogFor(o);if(o.kind!=='seller')return[];return AXES.map(key=>{const a=o.evidence.axes[key];return{key,title:AXIS_TITLES[key],site:c.sites[a.site].label,tool:a.tool,reference:a.reference,claim:o.talked.includes(key)?a.claim:null,observation:o.inspectionResults[a.tool+'-'+a.site]||null}})}
function appraisalReview(s){const o=s.current;if(o.kind!=='seller'||!['bought','sold'].includes(o.status))return[];return AXES.map(key=>{const a=o.evidence.axes[key],labels=key==='authenticity'?['모조품','진품']:key==='quality'?['거친 제작','고른 제작','정교한 제작']:['손상·수리 흔적','가벼운 사용 흔적','온전한 보존'];return{key,title:AXIS_TITLES[key],result:labels[a.actual],reference:a.reference,observation:a.full,seen:!!a.observedActual,claim:a.claim,explanation:a.claimed!==a.actual?(o.intent==='fraud'?'손님은 이 특징을 실제보다 좋게 말했습니다.':a.claimed<a.actual?'손님도 이 특징의 가치를 낮게 알고 있었습니다.':'손님이 알고 있던 설명과 실제 흔적이 달랐습니다.'):'이 특징에 관한 설명은 실제와 같았습니다.'}})}
function conversation(s,o){const p=profile(o.character);o.history=[];o.notes=[];o.talkLeft=0;o.patience=p.patience+(relationship(s,o.character)>=60?1:0);o.mood=Math.round(relationship(s,o.character)/5);o.relationDelta=0;o.talked=[];o.physicalUsed=false;o.suspicion=0;o.acceptedOffer=false;o.offerRelationApplied=false;o.lastOffer=null;o.leverage=0;o.checks=[];o.clues={};o.lastCheck=null;o.verdict='';o.feedback='';o.intentionRoll=rand(s);o.intent=o.intentionRoll>p.honesty?'fraud':o.genuine?'honest':'unaware';o.evidence={physical:rand(s)};o.rewarded={};delete o.investigations;delete o.investigationVersion;buildInvestigations(s,o)}
function sellerLot(s,character){const choices=items().filter(x=>x.id!==s.lastItemId),it=pick(s,choices.length?choices:items()),p=profile(character);const claimedGrade=tier(s),condition=Math.floor(rand(s)*5),genuine=rand(s)>=.23,sleeper=genuine&&rand(s)<.12,grade=sleeper?Math.min(8,claimedGrade+2+Math.floor(rand(s)*2)):claimedGrade;const apparent=Math.max(8,Math.round(it.base*GRADES[claimedGrade][2]*CONDITIONS[condition][1]));const value=Math.max(5,Math.round(genuine?it.base*GRADES[grade][2]*CONDITIONS[condition][1]:apparent*(.055+rand(s)*.16)));const asking=Math.max(12,Math.round(apparent*(.65+rand(s)*.5)));return{uid:'lot-'+s.serial,itemId:it.id,character,kind:'seller',grade,claimedGrade,condition,genuine,sleeper,apparent,value,estimate:Math.round(apparent*(.83+rand(s)*.34)),asking,price:asking,baseFloor:Math.max(4,Math.round(asking*(.61+p.frugality*.19+rand(s)*.1-s.upgrades.word*.009))),floor:0,paid:0,sale:0,attempts:0,status:'offered',wasFirst:false,line:null,negotiated:false}}
function availableStock(s){return s.stock.filter(x=>x.displayAt===null)}
function makeBuyerQuote(s,o,lot){const p=profile(o.character),it=item(lot.itemId),detected=!lot.genuine&&rand(s)<(.22+p.expertise*.65),taste=p.likes.includes(it.category)?1.28:p.dislikes.includes(it.category)?.76:1;const apparent=lot.apparent||Math.round(it.base*GRADES[lot.claimedGrade??lot.grade][2]*CONDITIONS[lot.condition??2][1]);const perceived=detected?lot.value:lot.genuine?lot.value:apparent;const base=Math.max(4,perceived*taste*marketFactor(s,it));return{uid:lot.uid,price:Math.max(3,Math.round(base*(.68+(1-p.frugality)*.15))),initialPrice:0,maxBase:Math.max(4,Math.round(base*(.98+(1-p.frugality)*.22+s.upgrades.word*.014))),perceivedValue:Math.round(base),detected,disclosed:false,acceptedOffer:false,lastOffer:null,taste,assertRoll:rand(s),asserted:false}}
function applyBuyerLot(s,o,lot){const q=o.buyerQuotes[lot.uid];o.stockUid=lot.uid;o.itemId=lot.itemId;o.grade=lot.grade;o.claimedGrade=lot.claimedGrade??lot.grade;o.condition=lot.condition??2;o.genuine=lot.genuine;o.value=lot.value;o.apparent=lot.apparent||lot.value;o.estimate=q.perceivedValue;o.paid=lot.paid;o.price=q.price;o.asking=q.initialPrice;o.acceptedOffer=q.acceptedOffer;o.lastOffer=q.lastOffer;o.sleeper=false;o.baseFloor=0;o.floor=0}
function roll(s){const candidates=chars().map((_,i)=>i).filter(i=>i!==s.lastCharacter),character=pick(s,candidates.length?candidates:[0]);s.serial++;s.met[character]=(s.met[character]||0)+1;const ready=availableStock(s),buyer=ready.length>0&&rand(s)<(s.stock.length>=capacity(s)-1?.7:.4);let o;if(buyer){const p=profile(character),preferred=ready.filter(x=>p.likes.includes(item(x.itemId).category)),lot=pick(s,preferred.length?preferred:ready);o={uid:'visit-'+s.serial,kind:'buyer',itemId:lot.itemId,character,grade:lot.grade,condition:lot.condition??2,genuine:lot.genuine,value:lot.value,asking:0,price:0,floor:0,baseFloor:0,paid:lot.paid,sale:0,attempts:0,status:'offered',line:null,wasFirst:false,negotiated:false,buyerQuotes:{}};conversation(s,o);for(const x of ready){const q=makeBuyerQuote(s,o,x);q.initialPrice=q.price;o.buyerQuotes[x.uid]=q}applyBuyerLot(s,o,lot)}else{o=sellerLot(s,character);conversation(s,o);o.floor=sellerFloor(s,o)}s.current=o;s.lastCharacter=character;s.lastItemId=o.itemId;const greeting=voice(s,buyer?'buyerOpen':'sellerOpen');o.line=greeting;history(o,'customer',greeting);if(!buyer)history(o,'customer',voice(s,o.intent==='unaware'?'uncertainClaim':'claim',{detail:o.evidence.axes.authenticity.claim}));}

function sellerFloor(s,o){return Math.max(3,Math.round(o.baseFloor*clamp(1-relationship(s,o.character)*.0017-o.mood*.0007-o.leverage,.48,1.28)))}
function buyerCeiling(s,o){const q=o.buyerQuotes?.[o.stockUid];return q?Math.max(3,Math.round(q.maxBase*clamp(1+relationship(s,o.character)*.0018+o.mood*.0008,.7,1.3))):0}
function openTrade(s){return !s.closing&&s.current?.status==='offered'}
function dialogueOptions(s){if(!openTrade(s))return[];const o=s.current,done=new Set(o.talked),out=[],add=(id,label,hint,tone)=>{if(!done.has(id))out.push({id,label,hint,...(tone?{tone}:{})})};
 if(o.kind==='buyer'){const q=o.buyerQuotes[o.stockUid];add('taste','어떤 물건을 찾으세요?','원하는 품목을 듣습니다.');add('rapport','거래에서 무엇이 중요한가요?','손님의 거래 성향을 듣습니다.');if(!q.storyShown)out.push({id:'story',label:'이 물건의 사연을 소개하기'});if(!o.genuine&&!q.disclosed)out.push({id:'disclose',label:'모조품이라는 사실을 알리기'});if(!q.asserted&&!q.disclosed)out.push({id:'assert-real',label:'진품임을 보증하기',hint:'손님이 아는 특징과 다르면 관계가 나빠집니다.',tone:'risk'});add('pressure','지금 결정해 달라고 재촉하기','재촉은 협상 여유를 줄입니다.','risk')}
 else{const c=catalogFor(o);for(const key of AXES)add(key,c[key].question,'이 물건의 특징을 직접 물어봅니다.');add('origin',c.provenance.question,'물건을 얻은 맥락을 듣습니다.');add('use',c.use.question,'사용·보관 경험을 듣습니다.');add('motive','왜 이 물건을 팔려고 하세요?','판매 사정을 듣습니다.');for(const key of AXES)if(done.has(key))add('challenge-'+key,c[key].topicLabel+' 설명이 달라요','직접 확인한 흔적으로 반박합니다. 근거가 없으면 관계가 나빠집니다.','risk');if(o.inspected.length)add('share-findings','좋은 세공을 발견했다고 알려주기','높은 제작 수준을 알리면 손님이 값을 올릴 수 있습니다.');add('accuse','증거 없이 가품이라고 단정하기','협상 여유와 호감도가 줄어듭니다.','hostile')}return out}
function leave(s){const o=s.current;o.patience=Math.max(0,o.patience);o.status='left';o.acceptedOffer=false;history(o,'customer',voice(s,'walk'))}
function talk(s,id){const option=dialogueOptions(s).find(x=>x.id===id);if(!option)return{ok:false,message:'이미 답한 주제는 전체 대화에서 다시 볼 수 있어요.'};const o=s.current,p=profile(o.character),it=item(o.itemId),c=catalogFor(o);o.relationDelta=0;if(!o.talked.includes(id))o.talked.push(id);history(o,'player',option.label);let text='';
 const reward=(key,amount,reason)=>{o.rewarded=o.rewarded||{};if(!o.rewarded[key]){changeRelation(s,amount,reason);o.rewarded[key]=true}};
 if(o.kind==='seller'&&AXES.includes(id))text=voice(s,o.intent==='unaware'?'uncertainClaim':'claim',{detail:o.evidence.axes[id].claim});
 else if(id==='origin'||id==='use'){const entries=id==='origin'?c.provenance.origins:c.use.answers;text=voice(s,'claim',{detail:entries[Math.floor(stable(o,id)*entries.length)]})}
 else if(id==='motive'){text=voice(s,'need');if(stable(o,'need')<.4)o.leverage=Math.min(.28,o.leverage+.04)}
 else if(id.startsWith('challenge-')){const a=o.evidence.axes[id.slice(10)],supported=a&&a.observedActual&&a.claimed!==a.actual;if(supported){history(o,'player','직접 본 흔적: '+a.full);text=voice(s,o.intent==='fraud'?'caught':'corrected');if(a.claimed>a.actual){const reduction=a.key==='authenticity'?.7:a.key==='quality'?.24:.14;o.baseFloor=Math.max(3,Math.round(o.baseFloor*(1-reduction)));o.asking=Math.max(4,Math.round(o.asking*(1-reduction)));o.price=Math.min(o.price,o.asking);o.acceptedOffer=false;o.lastOffer=null;}if(o.intent!=='fraud')reward('challenge',2,'차분하게 흔적을 확인함')}else{text=voice(s,'unfounded');changeRelation(s,-5,'뒷받침되지 않는 반박');o.mood=clamp(o.mood-10,-100,100);o.patience--}}
 else if(id==='share-findings'){const a=o.evidence.axes.quality;if(a.observedActual&&a.actual===2){text=voice(s,'corrected');reward('findings',4,'좋은 제작 수준을 알려줌');if(a.claimed<a.actual){o.baseFloor=Math.round(o.baseFloor*1.3);o.asking=Math.round(o.asking*1.3);o.price=Math.round(o.price*1.3);o.acceptedOffer=false;o.lastOffer=null;history(o,'note','손님이 제작 수준을 알고 희망 가격을 '+o.price.toLocaleString('ko-KR')+'G로 바꿨습니다.')}}else text=voice(s,'unfounded')}
 else if(id==='accuse'){text=voice(s,'offended');changeRelation(s,o.genuine?-12:-7,'근거를 대지 않은 단정');o.patience-=2;o.mood=clamp(o.mood-20,-100,100)}
 else if(id==='taste'){text=voice(s,'taste');if(o.buyerQuotes[o.stockUid].taste>1)o.mood=clamp(o.mood+8,-100,100)}
 else if(id==='rapport')text=voice(s,'rapport');
 else if(id==='story'){o.buyerQuotes[o.stockUid].storyShown=true;history(o,'player',it.story);text=voice(s,'story');const likes=p.likes.includes(it.category);if(!o.rewarded?.story)o.mood=clamp(o.mood+(likes?10:4),-100,100);reward('story',likes?3:1,'물건의 사연을 나눔')}
 else if(id==='disclose'){const q=o.buyerQuotes[o.stockUid];q.disclosed=true;q.detected=true;q.acceptedOffer=false;q.lastOffer=null;const base=o.value*q.taste*marketFactor(s,it);q.perceivedValue=Math.max(3,Math.round(base));q.maxBase=Math.max(3,Math.round(base*(1.08+(1-p.frugality)*.14)));q.price=Math.max(3,Math.round(base*.8));q.initialPrice=q.price;o.asking=q.initialPrice;o.price=q.price;o.acceptedOffer=false;o.lastOffer=null;o.estimate=q.perceivedValue;text=voice(s,'disclosed');reward('disclosed',4,'솔직한 설명')}
 else if(id==='assert-real'){const q=o.buyerQuotes[o.stockUid],caught=!o.genuine&&(q.detected||q.disclosed||q.assertRoll<(.16+p.expertise*.68));q.asserted=true;q.acceptedOffer=false;q.lastOffer=null;o.acceptedOffer=false;o.lastOffer=null;if(caught){q.detected=true;const base=Math.max(3,o.value*q.taste*marketFactor(s,it));q.perceivedValue=Math.round(base);q.maxBase=Math.max(3,Math.round(base*1.08));q.price=Math.max(3,Math.round(base*.72));changeRelation(s,-15,'거짓 보증을 알아챈 손님');o.mood=clamp(o.mood-25,-100,100);o.patience-=2}else{q.perceivedValue=Math.round(q.perceivedValue*1.1);q.maxBase=Math.round(q.maxBase*1.1);q.price=Math.round(q.price*1.08);if(!o.rewarded?.reassure)o.mood=clamp(o.mood+8,-100,100);reward('reassure',2,'보증을 믿는 손님')}o.price=q.price;o.estimate=q.perceivedValue;text=voice(s,caught?'offended':'reassure')}
 else if(id==='pressure'){text=voice(s,'pressure');const sensitive=p.temperament==='proud'||p.temperament==='suspicious';changeRelation(s,sensitive?-5:-3,'구매를 재촉함');o.mood=clamp(o.mood-(sensitive?15:7),-100,100);o.patience--;if(!sensitive)o.buyerQuotes[o.stockUid].maxBase=Math.round(o.buyerQuotes[o.stockUid].maxBase*1.04)}
 if(text)history(o,'customer',text);if(o.patience<=0)leave(s);o.floor=o.kind==='seller'?sellerFloor(s,o):0;return{ok:true,message:o.status==='left'?'손님이 문을 닫고 나갔습니다.':'이야기를 나눴습니다.',relationDelta:o.relationDelta}}
function offer(s,amount){if(!openTrade(s))return{ok:false,message:'진행 중인 거래가 없습니다.'};const o=s.current;if(!Number.isSafeInteger(amount)||amount<1||amount>MAX_OFFER)return{ok:false,message:'1~999,999,999G 사이의 정수 금액을 입력하세요.'};if(o.acceptedOffer)return{ok:false,message:'이미 합의한 가격입니다. 거래를 확정하거나 다른 물건을 고르세요.'};if(o.lastOffer===amount)return{ok:false,message:'같은 제안은 이미 전달했습니다.'};if(o.kind==='seller'&&amount>s.coins)return{ok:false,message:'가지고 있는 금액 안에서 제안하세요.'};if(o.kind==='buyer'&&!s.stock.some(x=>x.uid===o.stockUid&&x.displayAt===null))return{ok:false,message:'선택한 물건이 더 이상 보관함에 없습니다.'};o.relationDelta=0;o.attempts++;o.lastOffer=amount;history(o,'player',Math.round(amount).toLocaleString('ko-KR')+'G를 제안합니다.');const q=o.kind==='buyer'?o.buyerQuotes[o.stockUid]:null,limit=o.kind==='seller'?sellerFloor(s,o):buyerCeiling(s,o),accepted=o.kind==='seller'?amount>=limit:amount<=limit;
if(accepted){o.price=amount;o.acceptedOffer=true;o.negotiated=true;if(!o.offerRelationApplied){changeRelation(s,1,'제안을 받아들임');o.offerRelationApplied=true}history(o,'customer',voice(s,'offerAccepted'));if(q){q.price=o.price;q.acceptedOffer=true;q.lastOffer=amount}return{ok:true,accepted:true,message:'금액에 합의했습니다. 확정 버튼을 눌러 거래하세요.'}}
const extreme=o.kind==='seller'?amount<o.asking*.35:amount>q.perceivedValue*2.2;const repeat=o.attempts>2;const loss=extreme?(profile(o.character).temperament==='proud'?16:12):repeat?3:1;changeRelation(s,-loss,extreme?'모욕적인 가격 제안':repeat?'거듭된 무리한 흥정':'가격 차이');o.mood=clamp(o.mood-(extreme?22:7),-100,100);o.patience-=extreme?2:1;const newLimit=o.kind==='seller'?sellerFloor(s,o):buyerCeiling(s,o);o.price=o.kind==='seller'?Math.max(newLimit,Math.min(o.price,Math.round((o.price+newLimit)/2))):Math.min(newLimit,Math.max(o.price,Math.round((o.price+newLimit)/2)));o.floor=o.kind==='seller'?newLimit:0;if(q){q.price=o.price;q.lastOffer=amount}history(o,'customer',voice(s,extreme?'offended':'counter'));history(o,'note','손님의 새 제안: '+o.price.toLocaleString('ko-KR')+'G');if(o.patience<=0)leave(s);return{ok:true,accepted:false,message:o.status==='left'?'흥정이 끝났습니다. 손님이 떠났어요.':'상대가 '+o.price.toLocaleString('ko-KR')+'G를 다시 제안했습니다.',relationDelta:o.relationDelta}}
function chooseStock(s,uid){if(!openTrade(s)||s.current.kind!=='buyer')return{ok:false,message:'구매 손님이 있을 때 물건을 고를 수 있습니다.'};const o=s.current,lot=s.stock.find(x=>x.uid===uid&&x.displayAt===null);if(!lot||!o.buyerQuotes[uid])return{ok:false,message:'이번 손님에게 보여 줄 수 없는 물건입니다.'};if(o.stockUid===uid)return{ok:false,message:'이미 선택한 물건입니다.'};applyBuyerLot(s,o,lot);o.relationDelta=0;history(o,'player',item(lot.itemId).name+'을 보여 줍니다.');history(o,'customer',voice(s,'counter'));return{ok:true,message:'판매할 물건을 바꿨습니다.'}}
function achievements(s){for(const a of ACHIEVEMENTS){const value=a.key==='discovery'?Object.keys(s.discovered).length:s[a.key];if(value>=a.goal&&!s.claimed.includes(a.id)){s.claimed.push(a.id);s.coins+=a.reward;notify(s,'업적 · '+a.name+' +'+a.reward+'G');log(s,a.name+' 달성. 보상 '+a.reward+'G.','good')}}}
function buy(s){const o=s.current;if(!openTrade(s)||o.kind!=='seller')return{ok:false,message:'매입할 거래가 없습니다.'};if(s.coins<o.price)return{ok:false,message:'소지금이 부족해요. 보관함의 물건을 팔거나 손님을 보내세요.'};if(s.stock.length>=capacity(s))return{ok:false,message:'보관함이 가득 찼어요. 물건 하나를 팔아 자리를 비워 주세요.'};o.relationDelta=0;s.coins-=o.price;o.paid=o.price;o.status='bought';const lot={uid:o.uid,itemId:o.itemId,grade:o.grade,claimedGrade:o.claimedGrade,condition:o.condition,genuine:o.genuine,value:o.value,apparent:o.apparent,paid:o.price,displayAt:null,sourceCharacter:o.character};s.stock.push(lot);s.bought++;s.dayBought++;s.xp+=12+o.grade*3;if(o.grade>=3)s.rare++;if(o.grade>=6)s.legend++;const prev=s.discovered[o.itemId];s.discovered[o.itemId]={grade:Math.max(prev?.grade||0,o.grade),count:(prev?.count||0)+1,genuine:!!(prev?.genuine||o.genuine)};const satisfaction=o.price>=o.asking*.96?5:o.price>=o.asking*.78?3:o.price>=o.asking*.6?1:-1;changeRelation(s,satisfaction,'매입 거래의 만족도');o.verdict=o.genuine?(o.sleeper?'감정 뒤 숨은 세공이 드러났습니다. 예상보다 귀한 진품입니다.':'매입 뒤 정밀 확인을 마쳤습니다. 진품입니다.'):(o.intent==='unaware'?'모조품입니다. 이전 소유자는 진품으로 알고 가져왔습니다.':'모조품입니다. 손님은 출처를 꾸며 값을 높이려 했습니다.');if(o.genuine&&o.intent==='fraud'&&Object.values(o.evidence.axes).some(a=>a.claimed>a.actual))o.verdict+=' 진품이지만 제작 수준이나 보존 설명에는 과장이 있었습니다.';history(o,'note',o.verdict);log(s,item(o.itemId).name+' 매입 −'+o.price+'G',o.genuine?'normal':'warn');achievements(s);return{ok:true,message:o.verdict,lot,relationDelta:o.relationDelta}}
function settleSale(s,lot,amount){const ix=s.stock.findIndex(x=>x.uid===lot.uid);if(ix<0)return null;const profit=amount-lot.paid;s.coins+=amount;s.profit+=profit;s.dayProfit+=profit;s.sold++;s.xp+=8;s.stock.splice(ix,1);if(s.current?.uid===lot.uid){s.current.status='sold';s.current.sale=amount}log(s,item(lot.itemId).name+' 판매 +'+amount+'G (이익 '+(profit>=0?'+':'')+profit+'G)',profit>=0?'good':'warn');achievements(s);return{amount,profit}}
function accept(s){if(!openTrade(s))return{ok:false,message:'이미 처리되었거나 끝난 거래입니다.'};const o=s.current;if(o.kind==='seller')return buy(s);const lot=s.stock.find(x=>x.uid===o.stockUid&&x.displayAt===null),q=o.buyerQuotes?.[o.stockUid];if(!lot||!q)return{ok:false,message:'선택한 물건이 더 이상 보관함에 없습니다.'};o.relationDelta=0;const result=settleSale(s,lot,o.price);if(!result)return{ok:false,message:'이미 판매한 물건입니다.'};o.status='sold';o.sale=result.amount;const ratio=o.price/Math.max(1,q.perceivedValue);let satisfaction=ratio<=.82?6:ratio<=1.02?4:ratio<=1.22?2:-2;if(q.taste>1)satisfaction+=2;if(q.detected&&!q.disclosed)satisfaction-=2;changeRelation(s,satisfaction,'구매 손님이 느낀 거래 만족도');o.verdict=!lot.genuine?(q.disclosed?'모조품임을 알고 구매했습니다. 솔직한 설명이 신뢰를 남겼습니다.':q.detected?'손님은 복제 가능성을 알아보고 그에 맞는 값으로 구매했습니다.':'손님은 진품이라고 믿고 만족하며 가져갔습니다. 실제로는 모조품이었습니다.'):'손님이 물건과 가격을 확인하고 구매를 마쳤습니다.';history(o,'customer',voice(s,'offerAccepted'));history(o,'note',o.verdict);return{ok:true,message:'손님에게 판매했습니다. '+result.profit.toLocaleString('ko-KR')+'G 이익',...result,relationDelta:o.relationDelta}}
function sell(s,uid,mode='quick'){const lot=s.stock.find(x=>x.uid===uid);if(!lot)return{ok:false,message:'이미 판매한 물건입니다.'};if(openTrade(s)&&s.current.kind==='buyer'&&s.current.stockUid===uid)return{ok:false,message:'지금 손님과 흥정 중인 물건입니다. 거래를 확정하거나 손님을 보내세요.'};if(lot.displayAt!==null&&mode!=='complete')return{ok:false,message:'진열 판매를 기다리는 물건입니다.'};if(mode==='display'){if(s.stock.filter(x=>x.displayAt!==null).length>=displayCapacity(s))return{ok:false,message:'진열대가 가득 찼어요.'};lot.displayAt=s.turn+2;lot.displayPrice=quote(s,lot,'display');log(s,item(lot.itemId).name+' 진열. 손님 2명 뒤 판매됩니다.');return{ok:true,message:'손님 2명이 다녀가면 '+lot.displayPrice+'G에 판매돼요.'}}
if(!['quick','complete','request'].includes(mode))return{ok:false,message:'알 수 없는 판매 방식입니다.'};if(mode==='complete'&&(lot.displayAt===null||lot.displayAt>s.turn))return{ok:false,message:'아직 판매 시점이 아닙니다.'};const ev=event(s);if(mode==='request'&&(s.eventDone||ev.kind!=='request'||!lot.genuine||(ev.category!=='all'&&ev.category!==item(lot.itemId).category)))return{ok:false,message:'의뢰 조건에 맞지 않습니다.'};const amount=mode==='complete'?lot.displayPrice:mode==='request'?Math.round(lot.value*(ev.mult||1.4))+(ev.gift||0):quote(s,lot);if(mode==='request'){s.eventDone=true;s.xp+=35}const result=settleSale(s,lot,amount);if(mode==='complete')notify(s,'진열 판매 완료 · '+item(lot.itemId).name+' +'+amount+'G');return{ok:true,message:'판매 완료. '+(result.profit>=0?'+':'')+result.profit+'G 이익',...result}}
function next(s){if(s.closing)return{ok:false,message:'영업을 마감해 주세요.'};if(s.current.status==='offered')s.current.status='left';s.turn++;for(const lot of [...s.stock])if(lot.displayAt!==null&&lot.displayAt<=s.turn)sell(s,lot.uid,'complete');if(s.visitor>=8){s.closing=true;return{ok:true,closing:true}}s.visitor++;roll(s);return{ok:true}}
function nextDay(s){if(!s.closing)return{ok:false,message:'아직 영업 중입니다.'};const bonus=70+s.day*15;s.coins+=bonus;s.day++;s.visitor=1;s.dayBought=0;s.dayProfit=0;s.closing=false;s.xp+=15;log(s,'하루 정산 보너스 +'+bonus+'G. 새로운 밤이 시작됩니다.','good');selectEvent(s);s.dayStart=s.coins;roll(s);return{ok:true,message:'정산 보너스 +'+bonus+'G'}}
function upgrade(s,key){if(!Object.hasOwn(s.upgrades,key))return{ok:false,message:'알 수 없는 강화입니다.'};const cost=UPGRADE_COSTS[s.upgrades[key]];if(cost===undefined)return{ok:false,message:'최고 단계입니다.'};if(s.coins<cost)return{ok:false,message:'소지금이 부족합니다.'};s.coins-=cost;s.upgrades[key]++;log(s,({appraisal:'감정 도구',shelves:'보관함',word:'가게 평판'})[key]+' 강화 −'+cost+'G','good');return{ok:true,message:'가게가 한 단계 성장했어요.'}}
function aid(s){if(s.coins>=120||s.stock.length||s.aidDay===s.day)return{ok:false,message:'소지금 120G 미만, 재고가 없을 때 하루 한 번 받을 수 있어요.'};s.coins+=200;s.aidDay=s.day;log(s,'옆집 심부름을 마쳤다. +200G','good');return{ok:true,message:'심부름 보상 +200G'}}
function prepare(s){const oldVersion=s.version,o=s.current;if(oldVersion===3){s.relationships=s.relationships||{};s.lastCharacter=o.character;s.lastItemId=o.itemId;s.activeEvent=s.activeEvent?{...s.activeEvent,day:s.day}:{...clone(events()[((s.day-1)*7)%Math.max(1,events().length)]||event(s)),day:s.day};s.lastEventId=s.activeEvent.id||null;delete s.storyQueue;o.kind='seller';o.baseFloor=o.floor;o.apparent=o.apparent||Math.round(o.genuine?o.value:o.value/.13);o.estimate=o.estimate||o.apparent;o.claimedGrade=o.claimedGrade??o.grade;const seed=s.seed;conversation(s,o);s.seed=seed;o.wasFirst=false;o.line=null}
 if(oldVersion<5){o.legacyHistory=clone(o.history||[]);o.history=[];o.notes=[];o.talked=(o.talked||[]).filter(k=>['rapport','motive','accuse','pressure'].includes(k));o.rewarded={story:true,disclosed:true,reassure:true};o.talkLeft=0;delete o.investigationVersion;delete o.investigations;s.version=5}buildInvestigations(s,o);o.rewarded=o.rewarded||{};if(typeof o.offerRelationApplied!=='boolean')o.offerRelationApplied=!!(o.acceptedOffer||Object.values(o.buyerQuotes||{}).some(q=>q.acceptedOffer));if(o.kind==='buyer')for(const [uid,q] of Object.entries(o.buyerQuotes||{}))if(typeof q.assertRoll!=='number')q.assertRoll=stable(o,uid);
 if(oldVersion<5){history(o,'note','금고·재고·합의 금액을 이어받았습니다. 감정 방식이 바뀌어 이번 물건의 질문과 조사 기록을 새로 시작합니다.');history(o,'customer',voice(s,o.kind==='buyer'?'buyerOpen':'sellerOpen'))}for(const lot of s.stock){lot.condition=lot.condition??2;lot.claimedGrade=lot.claimedGrade??lot.grade;lot.apparent=lot.apparent||Math.round(lot.genuine?lot.value:lot.value/.13)}return s}
function validate(s){if(!s||![3,4,5].includes(s.version)||!finite(s.coins)||s.coins<0||!Array.isArray(s.stock)||!s.current)return false;if(!s.upgrades||!s.discovered||!s.met||!Array.isArray(s.claimed)||!Array.isArray(s.log)||!Array.isArray(s.notices))return false;if(!integer(s.day)||s.day<1||!integer(s.visitor)||s.visitor<1||s.visitor>8||typeof s.closing!=='boolean')return false;for(const k of ['appraisal','shelves','word'])if(!integer(s.upgrades[k])||s.upgrades[k]>5)return false;for(const k of ['seed','turn','serial','xp','bought','sold','rare','legend','dayBought','aidDay'])if(!integer(s[k]))return false;for(const k of ['profit','dayProfit','dayStart'])if(!finite(s[k]))return false;const o=s.current;if(!validItem(o.itemId)||!['offered','bought','sold','left'].includes(o.status)||!Array.isArray(o.checks)||!integer(o.grade)||o.grade>8||!integer(o.character)||o.character>=chars().length||!integer(o.attempts)||typeof o.genuine!=='boolean')return false;for(const k of ['value','asking','price','floor','paid','sale'])if(!finite(o[k])||o[k]<0)return false;if(typeof o.uid!=='string'||!integer(o.condition)||o.condition>4)return false;for(const [id,d] of Object.entries(s.discovered))if(!validItem(id)||!d||!integer(d.grade)||d.grade>8||!integer(d.count)||typeof d.genuine!=='boolean')return false;for(const [id,n] of Object.entries(s.met))if(!/^\d+$/.test(id)||Number(id)>=chars().length||!integer(n))return false;const ids=new Set();for(const lot of s.stock){if(typeof lot.uid!=='string'||!validItem(lot.itemId)||ids.has(lot.uid)||!finite(lot.value)||lot.value<0||!finite(lot.paid)||lot.paid<0||!integer(lot.grade)||lot.grade>8||typeof lot.genuine!=='boolean')return false;ids.add(lot.uid);if(lot.displayAt!==null&&(!integer(lot.displayAt)||!finite(lot.displayPrice)||lot.displayPrice<0))return false}
if(s.version>=4){if(s.version===4&&o.investigationVersion!==undefined){if(o.investigationVersion!==1||!integer(o.inspectionLeft)||o.inspectionLeft>2||!Array.isArray(o.inspected)||new Set(o.inspected).size!==o.inspected.length||o.inspected.length+o.inspectionLeft>2||!o.inspectionResults||!o.investigations)return false;for(const opt of INVESTIGATION_OPTIONS)if(typeof o.investigations[opt.id]!=='string')return false;for(const id of o.inspected)if(!INVESTIGATION_OPTIONS.some(x=>x.id===id)||typeof o.inspectionResults[id]!=='string')return false;}if(s.version===5){if(o.investigationVersion!==2||!o.evidence?.axes||!Array.isArray(o.inspected)||new Set(o.inspected).size!==o.inspected.length||o.inspected.length>6||!integer(o.inspectionLeft)||o.inspectionLeft+o.inspected.length!==6||!o.inspectionLevels||!o.inspectionResults||!o.investigations)return false;for(const opt of INVESTIGATION_OPTIONS)if(typeof o.investigations[opt.id]!=='string')return false;for(const k of AXES){const a=o.evidence.axes[k];if(!a||!['lens','light'].includes(a.tool)||!['mark','material','wear'].includes(a.site)||typeof a.reference!=='string'||typeof a.claim!=='string'||!integer(a.actual)||a.actual>(k==='authenticity'?1:2)||!integer(a.claimed)||a.claimed>(k==='authenticity'?1:2)||!integer(a.requiredLevel)||a.requiredLevel>5||typeof a.full!=='string')return false;}for(const id of o.inspected)if(!INVESTIGATION_OPTIONS.some(x=>x.id===id)||typeof o.inspectionResults[id]!=='string')return false;}if(!s.relationships||!s.activeEvent||s.activeEvent.day!==s.day||!['seller','buyer'].includes(o.kind)||!Array.isArray(o.history)||!Array.isArray(o.notes)||o.notes.some(x=>typeof x!=='string')||!Array.isArray(o.talked)||!integer(o.talkLeft)||o.talkLeft>4||!Number.isInteger(o.patience)||o.patience<0||o.patience>7||!finite(o.mood)||o.mood<-100||o.mood>100||!['honest','unaware','fraud'].includes(o.intent)||!o.evidence||typeof o.evidence.physical!=='number'||!finite(o.baseFloor)||typeof o.acceptedOffer!=='boolean')return false;for(const [key,n] of Object.entries(s.relationships))if(!/^\d+$/.test(key)||+key>=chars().length||!Number.isInteger(n)||n<-100||n>100)return false;if(o.history.some(x=>!x||!['player','customer','note'].includes(x.speaker)||typeof x.text!=='string'))return false;if(o.kind==='buyer'){const q=o.buyerQuotes?.[o.stockUid];if(!q||!finite(q.price)||!finite(q.maxBase)||!finite(q.perceivedValue)||!finite(q.initialPrice)||q.price<0||q.maxBase<0||q.perceivedValue<0)return false;if(o.status==='offered'&&!s.stock.some(x=>x.uid===o.stockUid&&x.displayAt===null))return false}}return true}
G.PawnEngine={GRADES,CATEGORIES,CONDITIONS,UPGRADE_COSTS,ACHIEVEMENTS,MAX_OFFER,create,prepare,validate,item,event,profile,relationship,relationLabel,dialogueOptions,talk,appraisalNotebook,appraisalReview,investigationOptions,investigationCost,investigate,offer,accept,chooseStock,capacity,displayCapacity,quote,buy,sell,next,nextDay,upgrade,aid,achievements};
})(globalThis);