'use strict';
(()=>{
const A=PawnApp,E=A.E,{esc,fmt,art,portrait}=A,$=id=>document.getElementById(id);
function goalsHTML(){return '<div class="eyebrow">세 가지 기록은 함께 쌓입니다</div><h3>어떤 가게를 만들고 싶나요?</h3><div class="goal-cards">'+E.goals(A.state).map(g=>'<button class="goal-card '+(A.state.ambition===g.id?'selected':'')+'" data-ambition="'+g.id+'" aria-pressed="'+(A.state.ambition===g.id)+'"><span>'+esc(g.name)+'</span><b>'+fmt(g.value)+' / '+fmt(g.target)+g.unit+'</b><progress max="'+g.target+'" value="'+Math.max(0,g.value)+'"></progress><small>'+esc(g.tip)+'</small><small>'+(g.finished?'마지막 목표 달성':g.completed+'개 이정표 달성')+(A.state.ambition===g.id?' · 관심 목표':'')+'</small></button>').join('')+'</div>'}
function albumHTML(){const s=A.state;return '<details class="album-panel"><summary>✦ 나의 테마 도록 · '+Object.keys(s.album).length+' / 144종 · '+s.albumRewards.length+' / 6세트</summary><p>진품을 보관했다가 마감 후 등록하세요. 등록한 물건은 팔아도 기록이 남습니다. 각 테마 4종을 완성하면 짧은 이야기와 120G를 받습니다.</p>'+E.COLLECTIONS.map(c=>'<article class="album-set"><h3>'+esc(c.name)+' <small>'+c.items.filter(id=>s.album[id]).length+'/4</small></h3><div class="album-items">'+c.items.map(id=>'<div class="'+(s.album[id]?'registered':'unregistered')+'">'+art(id,s.album[id]?.grade||1)+'<span>'+esc(E.item(id).name)+'</span><small>'+(s.album[id]?'기록 완료':'미등록')+'</small></div>').join('')+'</div>'+(s.albumRewards.includes(c.id)?'<p class="album-story">'+esc(c.story)+'</p>':'<p class="quiet-note">완성하면 이 물건들을 잇는 이야기가 열립니다.</p>')+'</article>').join('')+'</details>'}
function render(){const s=A.state;document.body.classList.toggle('after-hours',s.closing);$('goal-hub').innerHTML=goalsHTML();$('theme-album').innerHTML=albumHTML();if(!s.closing)return;const n=s.night,options=E.nightOptions(s),can=o=>n.actions>0&&s.coins>=o.cost,button=(o,detail)=>'<button class="night-option" data-night="'+o.kind+'" data-night-id="'+esc(o.id)+'" '+(!can(o)?'disabled':'')+'>'+(o.itemId?art(o.itemId):portrait(o.character))+'<span><strong>'+esc(o.label)+'</strong><small>'+detail+'</small><b>시간 1칸 · '+(o.cost?fmt(o.cost)+'G':'무료')+'</b></span></button>';
const catalog=options.filter(x=>x.kind==='catalog'),tea=options.filter(x=>x.kind==='tea'),repair=options.filter(x=>x.kind==='repair');
$('closing-view').innerHTML='<section class="after-hours-card"><div class="night-heading"><span class="eyebrow">문을 닫은 뒤에도, 가게의 밤은 계속됩니다</span><h2>'+s.day+'번째 밤의 자유 시간</h2><strong class="night-budget">남은 시간 '+n.actions+' / 2</strong></div><p>오늘 순이익 '+fmt(s.dayProfit)+'G · 다음 영업 전 정산 보너스 '+E.dayBonus(s).total+'G</p><p>두 칸을 원하는 곳에 쓰세요. 남은 시간을 쉬어도 불이익은 없습니다. 기본 지원은 자산 650G 미만일 때 최대 50G, 활동 보너스는 하루 최대 120G입니다.</p><div class="night-report" aria-live="polite">'+n.report.map(t=>'<p>'+esc(t)+'</p>').join('')+'</div><div class="night-activities"><details open><summary>▤ 진품 도록 쓰기 <small>수집</small></summary><p>등록해 두면 팔아도 소장 기록은 남습니다. 가품은 등록할 수 없습니다. 가격표를 단 진품도 기록할 수 있어요.</p>'+ (catalog.length?catalog.map(o=>button(o,'진품 기록 · 보관함에서 사라지지 않아요')).join(''):'<p class="quiet-note">등록할 새 진품이 없어요. 영업 중 새 진품을 사서 밤까지 보관해 보세요.</p>')+'</details><details><summary>♡ 단골과 차 한 잔 <small>관계</small></summary><p>호감도 +6. 25가 되면 마음속 이야기가 열립니다. 우호적인 손님일수록 다음 흥정에도 너그러워요.</p>'+tea.map(o=>button(o,'호감도 '+E.relationship(s,o.character)+' → '+Math.min(100,E.relationship(s,o.character)+6))).join('')+'</details><details><summary>⌕ 보관한 물건 손질 <small>가치</small></summary><p>보존 상태를 한 단계 개선합니다. 가품이 진품이 되지는 않아요. 비용은 원가에 포함되어 판매 이익에서 빠집니다.</p>'+(repair.length?repair.map(o=>button(o,'판매 가치 참고 '+fmt(o.before)+' → '+fmt(o.resale)+'G')).join(''):'<p class="quiet-note">손질할 재고가 없어요. 가격표를 단 물건도 손질할 수 있습니다.</p>')+'</details></div><details class="night-goals"><summary>나의 세 가지 목표 확인·변경</summary>'+goalsHTML()+'</details>'+albumHTML()+'<button class="btn primary wide" data-action="next-day">'+(n.actions?'남은 시간 쉬고 다음 영업으로':'정산하고 다음 영업으로')+'</button></section>';
}
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b||b.disabled)return;if(b.dataset.ambition)A.run(E.setAmbition,b.dataset.ambition);if(b.dataset.night){A.run(E.nightAction,b.dataset.night,b.dataset.nightId);requestAnimationFrame(()=>document.querySelector('#closing-view .night-report')?.scrollIntoView({block:'center',behavior:'smooth'}))}});
window.PawnNight={render};A.render();
})();
