'use strict';
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
for(const f of ['items.js','characters.js','profiles.js','appraisal-data.js','legacy-item-appraisals.js','item-appraisals.js','guest-data.js','voices.js','trade-voice.js','affinity-voice.js','origin-data.js','customer-goals.js','evolution.js','discovery-data.js','discovery.js','engine.js'])vm.runInThisContext(fs.readFileSync(path.join(__dirname,f),'utf8'),{filename:f});
const E=PawnEngine,copy=x=>JSON.parse(JSON.stringify(x));let tests=0;
function test(name,fn){fn();tests++;console.log('PASS '+name)}
function unchanged(s,fn){const before=JSON.stringify(s);assert.equal(fn().ok,false);assert.equal(JSON.stringify(s),before)}
function seller(rel=0,index=0){const s=E.create(85123),o=s.current;s.coins=100000;s.relationships={[index]:rel};Object.assign(o,{character:index,itemId:'clock-01',price:200,asking:200,baseFloor:140,patience:6,mood:0});delete o.investigationVersion;E.prepare(s);return s}
function buyer(rel=0){const s=seller(rel),o=s.current;
 s.stock=[['c','clock-01'],['c2','clock-02'],['j','jewelry-01'],['w','weapon-01'],['b','book-01']].map(([uid,itemId])=>({uid,itemId,grade:3,claimedGrade:3,condition:3,genuine:true,value:400,apparent:400,paid:200,displayAt:null,sourceCharacter:0}));
 Object.assign(o,{kind:'buyer',uid:'buyer-fixture',stockUid:'c',paid:200,value:400,apparent:400,price:300,asking:300,baseFloor:0,floor:0,buyerQuotes:{},purchasePurpose:PawnCustomerGoals.create(o,s.stock[0],E.item('clock-01'),'시계',()=>.1)});
 for(const l of s.stock)o.buyerQuotes[l.uid]={price:300,initialPrice:300,maxBase:440,perceivedValue:400,detected:false,disclosed:false,acceptedOffer:false,lastOffer:null,taste:E.profile(0).likes.includes(E.item(l.itemId).category)?1.28:1,assertRoll:.9,asserted:false};
 return s;
}
test('Both sides receive 1/2/3/4 offers at all affinity boundaries',()=>{for(const fn of [seller,buyer])for(const [n,max] of [[-100,1],[-25,1],[-24,2],[24,2],[25,3],[59,3],[60,4],[100,4]]){const s=fn(n);assert.equal(s.current.offerMax,max);assert.equal(s.current.offerLeft,max)}});
test('Two ordinary rejected offers leave the last quote available for checkout',()=>{const s=seller();assert.equal(E.offer(s,100).accepted,false);assert.equal(s.current.offerLeft,1);assert.equal(E.offer(s,110).accepted,false);assert.equal(s.current.offerLeft,0);assert.equal(s.current.status,'offered');unchanged(s,()=>E.offer(s,120));assert(E.accept(s).ok);assert(E.validate(s))});
test('Offer costs stay separate from question and inspection budgets',()=>{const s=seller(),o=s.current,q=o.talkLeft,i=o.inspectionLeft;E.offer(s,100);assert.equal(o.talkLeft,q);assert.equal(o.inspectionLeft,i);assert.equal(o.offerSpent,1)});
test('An accepted first offer can be followed by an explicit gamble using the remaining chance',()=>{const s=seller();assert(E.offer(s,190).accepted);unchanged(s,()=>E.offer(s,180));assert(E.reopenOffer(s).ok);assert.equal(s.current.offerLeft,1);assert(!s.current.acceptedOffer);assert(E.offer(s,180).accepted);assert.equal(s.current.offerLeft,0);unchanged(s,()=>E.reopenOffer(s));assert(E.validate(s))});
test('Continuing a deal after agreement can lose the entire transaction',()=>{const s=seller();E.offer(s,190);E.reopenOffer(s);assert(E.offer(s,1).departed);assert.equal(s.current.status,'left');unchanged(s,()=>E.accept(s));assert.equal(s.stock.length,0);assert.equal(s.coins,100000)});
test('Moderately insulting proposals spend two chances without earning a better counteroffer',()=>{const s=seller(80),o=s.current,before=o.price;const r=E.offer(s,60);assert(r.extreme);assert.equal(r.offerCost,2);assert.equal(o.price,before);assert.equal(o.offerSpent,2);assert.equal(o.offerLeft,2);assert.equal(o.status,'offered');assert(E.validate(s))});
test('Severe insults, proud sellers and unfriendly customers end the deal',()=>{for(const [n,index,price] of [[0,0,1],[0,8,60],[-30,0,60]]){const s=seller(n,index);assert(E.offer(s,price).departed);assert(s.current.bargainEndReason);unchanged(s,()=>E.accept(s));assert(E.validate(s))}});
test('Buyers also reject ridiculous markups and preserve the original quote',()=>{const s=buyer(80),price=s.current.price;assert(E.offer(s,1000).extreme);assert.equal(s.current.offerSpent,2);assert.equal(s.current.price,price);assert.equal(s.current.status,'offered');const severe=buyer();assert(E.offer(severe,2000).departed)});
test('Affinity changes alter remaining offers without refunding spent proposals',()=>{const s=seller(25);E.offer(s,100);assert.equal(E.relationship(s,0),24);assert.equal(s.current.offerMax,2);assert.equal(s.current.offerLeft,1);const before=s.current.offerSpent;s.relationships[0]=60;E.prepare(s);assert.equal(s.current.offerMax,4);assert.equal(s.current.offerSpent,before);assert.equal(s.current.offerLeft,3)});
test('Save and inventory switching preserve spent proposals and buyer purpose',()=>{const s=buyer();E.offer(s,500);const purpose=copy(s.current.purchasePurpose),spent=s.current.offerSpent;assert(E.chooseStock(s,'j').ok);assert(E.chooseStock(s,'c').ok);assert.equal(s.current.offerSpent,spent);assert.deepEqual(s.current.purchasePurpose,purpose);const loaded=E.prepare(copy(s));assert.deepEqual(loaded,s);assert(E.validate(loaded))});
test('Existing saves migrate offer use once while preserving negotiated money and history',()=>{const s=seller();E.offer(s,190);const price=s.current.price,h=copy(s.current.history);for(const k of ['offerVersion','offerMax','offerSpent','offerPenalty','offerWarnings','offerLeft'])delete s.current[k];assert(E.validate(s));E.prepare(s);assert.equal(s.current.offerSpent,1);assert.equal(s.current.price,price);assert.deepEqual(s.current.history,h);assert(s.current.acceptedOffer);const text=JSON.stringify(s);E.prepare(s);assert.equal(JSON.stringify(s),text)});
test('Purpose and favorite alternatives can be shown, unrelated stock is refused',()=>{const s=buyer();assert(E.buyerFit(s,s.stock.find(l=>l.uid==='c2')).allowed);assert(E.chooseStock(s,'j').ok);const selected=s.current.stockUid,offers=s.current.offerLeft;const r=E.chooseStock(s,'w');assert.equal(r.declined,true);assert.equal(s.current.stockUid,selected);assert.equal(s.current.offerLeft,offers);assert(s.current.history.at(-2).text.includes('weapon')===false);assert(!E.buyerFit(s,s.stock.find(l=>l.uid==='b')).allowed);assert(E.validate(s))});
test('Buyer conditions exclude unsuitable condition and workmanship even within the correct category',()=>{const s=buyer(),l=s.stock.find(x=>x.uid==='c2');l.condition=0;assert(!E.buyerFit(s,l).allowed);l.condition=3;l.grade=0;assert(!E.buyerFit(s,l).allowed)});
test('API cannot sell unrelated stock even if a selection is tampered with',()=>{const s=buyer();s.current.stockUid='w';unchanged(s,()=>E.offer(s,1));unchanged(s,()=>E.accept(s))});
test('Purchase questions reveal requirements, actionable budget and pitch preference',()=>{const s=buyer(60);E.prepare(s);E.talk(s,'taste');assert(s.current.feedback.includes('보존'));E.talk(s,'budget');assert.equal(s.current.buyerQuotes.c.knownBudget,396);E.talk(s,'rapport');assert(s.current.feedback.includes(E.pitchHint(s).slice(0,7)));assert(E.chooseStock(s,'j').ok);assert(E.talk(s,'budget').ok);assert.equal(s.current.questionSpent,4);assert(s.current.buyerQuotes.j.knownBudget)});
test('Every new purpose is suitable, stable on reload and most buyers visit for favorites',()=>{const s=E.create(117821);s.stock=Object.keys(E.CATEGORIES).map((cat,n)=>{const it=PAWN_ITEMS.find(x=>x.category===cat);return{uid:'all-'+n,itemId:it.id,grade:3,claimedGrade:3,condition:3,genuine:true,value:400,apparent:400,paid:100,displayAt:null,sourceCharacter:0}});s.upgrades.shelves=4;let buyers=0,favorites=0;for(let i=0;i<700;i++){s.closing?E.nextDay(s):E.next(s);if(s.current.kind!=='buyer')continue;buyers++;const o=s.current,lot=s.stock.find(l=>l.uid===o.stockUid);assert(E.buyerFit(s,lot).allowed);assert(o.purchasePurpose.name);if(E.profile(o.character).likes.includes(E.item(lot.itemId).category))favorites++;const text=JSON.stringify(s);assert.equal(JSON.stringify(E.prepare(copy(s))),text);assert(E.validate(s))}assert(buyers>250);assert.equal(buyers,favorites)});
test('Specialist sellers resist unsupported price cutting but a demonstrated defect still lowers demand',()=>{const s=seller();const plain=copy(s);plain.current.character=2;const specialist=E.offer(s,145),ordinary=E.offer(plain,145);assert.equal(specialist.accepted,false);assert.equal(ordinary.accepted,true);const fake=seller();fake.current.genuine=false;fake.current.practiceClassic=true;fake.current.appraisalClarity=0;delete fake.current.investigationVersion;E.prepare(fake);const a=fake.current.evidence.axes.authenticity;E.investigate(fake,a.tool+'-'+a.site);const p=fake.current.price;assert(E.presentEvidence(fake,'authenticity','defect').supported);assert(fake.current.price<p)});
test('Corrupted offer counters and purpose data are rejected without mutation',()=>{for(const mutate of [s=>s.current.offerLeft=99,s=>s.current.offerSpent=-1,s=>s.current.offerPenalty=9,s=>s.current.purchasePurpose.category='missing',s=>s.current.purchasePurpose.itemId='missing']){const s=buyer();mutate(s);const text=JSON.stringify(s);assert(!E.validate(s));assert.equal(JSON.stringify(s),text)}});
console.log(JSON.stringify({v69Tests:tests}));
