'use strict';
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const files=['items.js','characters.js','profiles.js','appraisal-data.js','legacy-item-appraisals.js','item-appraisals.js','guest-data.js','voices.js','trade-voice.js','affinity-voice.js','origin-data.js','customer-goals.js','evolution.js','dialogue-data.js','dialogue-reply.js','discovery-data.js','discovery.js','engine.js'];
for(const file of files)vm.runInThisContext(fs.readFileSync(path.join(__dirname,file),'utf8'),{filename:file});
const E=PawnEngine,V=PawnEvolution,copy=x=>JSON.parse(JSON.stringify(x));let passed=0;
function test(name,fn){try{fn();passed++;console.log('PASS '+name)}catch(e){console.error('FAIL '+name);throw e}}
function unchanged(s,fn){const before=JSON.stringify(s);assert.equal(fn().ok,false);assert.equal(JSON.stringify(s),before)}
function fixture(genuine=true,kind=0,id='clock-01',grade=6){
 const s=E.create(151),o=s.current;s.coins=100000;s.upgrades={appraisal:5,inspection:4,shelves:0,word:0};
 for(let k=0;k<200;k++){Object.assign(o,{uid:'review-'+k,itemId:id,genuine,grade,claimedGrade:3,condition:2,appraisalClarity:0,practiceClassic:false,intent:genuine?'honest':'fraud',talked:[],checks:[],history:[],notes:[]});delete o.investigationVersion;delete o.investigations;E.prepare(s);if(o.caseKind===kind)return s;}throw Error('fixture variant not found');
}
function see(s,axis){const a=s.current.evidence.axes[axis];return E.investigate(s,a.tool+'-'+a.site)}
function buyer(index){const s=E.create(533);s.coins=100000;for(let i=0;i<2;i++)s.stock.push({uid:'sale-'+i,itemId:i?'book-01':'clock-01',grade:3,claimedGrade:3,condition:2,genuine:true,value:450,apparent:450,paid:200,displayAt:null,sourceCharacter:0});for(let i=0;i<40;i++){if(s.current.kind==='buyer'){
 if(index!==undefined){const o=s.current;o.character=index;const p=E.profile(index),goods=PAWN_ITEMS.filter(x=>x.category===p.likes[0]);s.stock.forEach((lot,n)=>{lot.itemId=goods[n].id;const q=o.buyerQuotes[lot.uid];Object.assign(q,{price:450,initialPrice:450,maxBase:650,perceivedValue:600,taste:1.28})});const selected=s.stock.find(l=>l.uid===o.stockUid);o.itemId=selected.itemId;o.price=450;o.asking=450;o.purchasePurpose=PawnCustomerGoals.create(o,selected,E.item(selected.itemId),E.CATEGORIES[p.likes[0]],()=>.5);}
 return s;
}s.closing?E.nextDay(s):E.next(s)}throw Error('buyer missing')}
function arrival(s,kind){V.queue(s,kind,s.current,kind==='complaint'||kind==='undervalued'?80:0,0);const record=s.followups.find(x=>x.kind===kind);record.due=s.turn;s.lastCharacter=-1;for(let i=0;i<50;i++){s.closing?E.nextDay(s):E.next(s);if(s.current.returnStory?.id===record.id)return s.current.returnStory;}throw Error('return did not arrive')}

test('Cautious and confident answers occur with both genuine and fake objects',()=>{const s=E.create(1102),counts={realCautious:0,fakeCautious:0,realConfident:0,fakeConfident:0};for(let i=0;i<800;i++){if(!s.closing){const o=s.current;counts[(o.genuine?'real':'fake')+(V.cautious(o)?'Cautious':'Confident')]++;E.talk(s,'authenticity');assert(o.history.some(x=>x.speaker==='customer'));E.next(s)}else E.nextDay(s)}for(const n of Object.values(counts))assert(n>20);console.log(JSON.stringify(counts))});
test('All 144 items support genuine and fake surface/assembly variants with physical counter-evidence',()=>{for(const it of PAWN_ITEMS)for(const kind of [1,2])for(const genuine of [true,false]){const s=fixture(genuine,kind,it.id);see(s,'authenticity');assert(!s.current.evidence.axes.authenticity.observedActual);const initial=s.current.price;const clone=copy(s);assert.equal(E.presentEvidence(clone,'authenticity','defect').supported,false);assert(E.deepInvestigate(s,'deep-auth').ok);assert(s.current.evidence.axes.authenticity.observedActual);const result=E.presentEvidence(s,'authenticity',genuine?'praise':'defect');assert(result.supported);if(!genuine)assert(s.current.price<initial);assert(E.validate(s))}});
test('Deep actions need the first observation and the matching workbench level',()=>{const s=fixture(false,1);s.upgrades.inspection=0;unchanged(s,()=>E.deepInvestigate(s,'deep-auth'));see(s,'authenticity');unchanged(s,()=>E.deepInvestigate(s,'deep-auth'));assert(E.upgrade(s,'inspection').ok);assert(E.deepInvestigate(s,'deep-auth').ok);unchanged(s,()=>E.deepInvestigate(s,'deep-grade'));});
test('Six opportunities can cover three base observations and three deeper checks',()=>{const s=fixture(true,2);for(const axis of ['authenticity','quality','condition'])assert(see(s,axis).ok);for(const id of ['deep-auth','deep-grade','deep-wear'])assert(E.deepInvestigate(s,id).ok);assert.equal(s.current.inspectionLeft,0);assert.equal(s.current.inspectionSpent,6);const before=JSON.stringify(s);assert(E.deepInvestigate(s,'deep-grade').repeated);assert.equal(JSON.stringify(s),before);assert(E.validate(s))});
test('All nine grades have distinct readable signatures without disclosing price',()=>{const messages=new Set();for(let grade=0;grade<9;grade++){const s=fixture(true,0,'clock-01',grade);see(s,'quality');E.deepInvestigate(s,'deep-grade');const text=s.current.deepResults['deep-grade'];messages.add(text);assert(!text.includes('G'));assert(E.deepReference().includes(E.GRADES[grade][0]));}assert.equal(messages.size,9)});
test('A signature supports price negotiations even within the same broad quality band',()=>{for(const direction of [-1,1]){const s=fixture(true,0,'clock-01',direction<0?5:7),o=s.current;o.claimedGrade=direction<0?7:5;o.evidence.axes.quality.claimed=2;see(s,'quality');E.deepInvestigate(s,'deep-grade');assert.equal(V.qualityDirection(o),direction);const price=o.price;assert(E.presentEvidence(s,'quality',direction<0?'defect':'praise').supported);assert(direction<0?o.price<price:o.price>price);assert(o.history.some(h=>h.speaker==='player'&&h.text.includes(o.deepResults['deep-grade'])));assert(E.validate(s))}});
test('Greater insight requires an explicit paid reread and never rerolls a signature',()=>{const s=fixture(true,0);s.upgrades.appraisal=1;see(s,'quality');E.deepInvestigate(s,'deep-grade');const old=s.current.deepResults['deep-grade'],left=s.current.inspectionLeft;assert(E.upgrade(s,'appraisal').ok);assert.equal(s.current.deepResults['deep-grade'],old);E.deepInvestigate(s,'deep-grade');assert.notEqual(s.current.deepResults['deep-grade'],old);assert.equal(s.current.inspectionLeft,left-1);const saved=JSON.stringify(s);E.prepare(s);assert.equal(JSON.stringify(s),saved);assert(E.validate(s))});
test('Unread or unaffordable deeper checks fail without mutating the save',()=>{const s=fixture(false,2);see(s,'authenticity');s.current.inspectionSpent=s.current.inspectionMax;s.current.inspectionLeft=0;unchanged(s,()=>E.deepInvestigate(s,'deep-auth'));unchanged(s,()=>E.deepInvestigate(s,'not-an-id'))});
test('All 26 customers reward a matching pitch and reject repeated pitches across stock changes',()=>{for(let i=0;i<26;i++)for(const id of ['story','demonstrate','assert-real']){const s=buyer(i),o=s.current;o.patience=6;const price=o.price,questions=o.talkLeft,matched=V.approach(s)===id;assert(E.talk(s,id).ok);assert.equal(o.patience,5);assert.equal(o.talkLeft,questions);assert.equal(o.price>price,matched);const next=s.stock.find(x=>x.uid!==o.stockUid);assert(E.chooseStock(s,next.uid).ok);for(const other of ['story','demonstrate','assert-real'])unchanged(s,()=>E.talk(s,other));assert(E.validate(s))}});
test('Agreement cannot be repriced by a late sales presentation',()=>{const s=buyer();assert(E.offer(s,1).accepted);for(const id of ['story','demonstrate','assert-real'])unchanged(s,()=>E.talk(s,id));});
test('26 friends are required for the final goal',()=>{const s=E.create(3);for(let i=0;i<24;i++)s.relationships[i]=25;assert(!E.goals(s).find(g=>g.id==='friends').finished);s.relationships[24]=s.relationships[25]=25;assert(E.goals(s).find(g=>g.id==='friends').finished);});
test('One hundred idle nights cannot accumulate upgrade money',()=>{const s=E.create(32911),start=s.coins;for(let day=0;day<100;day++){while(!s.closing)E.next(s);assert.equal(E.dayBonus(s).activity,0);E.nextDay(s)}assert.equal(s.coins,start);assert.equal(s.profit,0);console.log('Idle 100 nights: '+s.coins+'G');});
test('Recovery support is bounded by assets and activity bonus by 120G',()=>{const s=E.create(72);s.coins=0;assert.equal(E.dayBonus(s).support,50);s.coins=649;assert.equal(E.dayBonus(s).support,1);s.coins=650;assert.equal(E.dayBonus(s).support,0);s.dayActivity={trades:32,night:2};assert.equal(E.dayBonus(s).activity,120)});
test('Later gift events wait for an activity and pay exactly once',()=>{const s=fixture();s.day=2;s.activeEvent={id:'gift-check',day:2,kind:'gift',gift:120};s.eventDone=false;const price=s.current.price,cash=s.coins;E.accept(s);assert.equal(s.coins,cash-price+120+(s.claimed.includes('first')?60:0)+(s.claimed.includes('legend')?900:0));const before=s.coins;V.activity(s,'trades');assert.equal(s.coins,before);assert(s.eventDone)});
test('Returning complaint survives reload and compensation pays only once',()=>{const s=fixture();const m=arrival(s,'complaint');assert(!m.resolved);const saved=JSON.stringify(s);E.prepare(s);assert.equal(JSON.stringify(s),saved);const cash=s.coins,profit=s.profit;assert(E.resolveFollowup(s,'compensate').ok);assert.equal(s.coins,cash-80);assert.equal(s.profit,profit-80);unchanged(s,()=>E.resolveFollowup(s,'compensate'));assert(s.memories.some(x=>x.id===m.id));assert(E.validate(s));});
test('A customer can be answered without money and leaving is not a forced fine',()=>{for(const id of ['explain','dismiss','skip']){const s=fixture();arrival(s,'complaint');s.coins=0;unchanged(s,()=>E.resolveFollowup(s,'compensate'));if(id==='skip')E.next(s);else assert(E.resolveFollowup(s,id).ok);assert.equal(s.coins,0);assert(E.validate(s))}});
test('Choosing a future favor leads to the promised customer and a real discounted item',()=>{const s=fixture();arrival(s,'gratitude');assert(E.resolveFollowup(s,'favor').ok);const q=s.followups.find(x=>x.kind==='favor-reward');assert(q);q.due=s.turn;for(let i=0;i<50;i++){s.closing?E.nextDay(s):E.next(s);if(s.current.returnStory?.id===q.id)break}assert.equal(s.current.returnStory?.id,q.id);assert.equal(s.current.kind,'seller');assert(s.current.genuine);assert(s.current.price<s.current.value);assert(s.current.returnStory.resolved);assert(E.validate(s))});
test('Every follow-up response is voiced in the current character register',()=>{const s=fixture();arrival(s,'apology');s.current.character=0;assert(E.resolveFollowup(s,'forgive').ok);assert(s.current.history.filter(x=>x.speaker==='customer').at(-1).text.includes('냥'));});
test('Corrupted extension data is rejected without throwing',()=>{const s=fixture(),variants=[];for(const mutate of [x=>x.current=null,x=>x.followups=[{id:'bad'}],x=>x.dayActivity.trades=99,x=>x.current.pitchUsed='yes',x=>x.current.deepResults={'unknown':'x'},x=>x.current.caseKind=9]){const c=copy(s);mutate(c);variants.push(c)}for(const c of variants)assert.equal(E.validate(c),false)});
test('Existing v6 saves keep all observed text, money, relationships and negotiated amounts',()=>{const old=JSON.parse(fs.readFileSync(path.join(__dirname,'migration-v6-fixture.json'))),before=copy(old);assert(E.validate(old));E.prepare(old);for(const k of ['coins','stock','relationships','seed'])assert.deepEqual(old[k],before[k]);for(const k of ['history','evidence','inspectionResults','price','acceptedOffer'])assert.deepEqual(old.current[k],before.current[k]);assert(!old.current.caseEdition);assert(E.validate(old));const twice=JSON.stringify(old);E.prepare(old);assert.equal(JSON.stringify(old),twice);});
test('Two thousand mixed encounters exercise deep clues, presentations and remembered transactions',()=>{const s=E.create(19091);s.coins=300000;s.upgrades={appraisal:3,inspection:4,shelves:5,word:2};let returns=0,pitches=0,deep=0;for(let i=0;i<2000;i++){if(s.closing){const option=E.nightOptions(s).find(x=>x.kind==='catalog');if(option)E.nightAction(s,option.kind,option.id);E.nextDay(s);continue}const o=s.current;if(E.returnChoices(s).length){const choice=E.returnChoices(s).find(x=>x.cost===0);assert(E.resolveFollowup(s,choice.id).ok);returns++}if(o.kind==='seller'){see(s,'authenticity');see(s,'quality');for(const id of ['deep-auth','deep-grade'])if(E.deepOptions(s).find(x=>x.id===id)?.enabled){assert(E.deepInvestigate(s,id).ok);deep++}if(o.price<s.coins&&s.stock.length<E.capacity(s))E.accept(s);}else{assert(E.talk(s,V.approach(s)).ok);pitches++;E.accept(s)}if(s.stock.length>E.capacity(s)-2){const lot=s.stock.find(x=>x.displayAt===null&&x.uid!==s.current.stockUid);if(lot)E.sell(s,lot.uid)}assert(E.validate(s));const reload=copy(s);E.prepare(reload);assert(E.validate(reload));assert.deepEqual(reload.current.deepResults,s.current.deepResults);E.next(s)}assert(pitches>100);assert(deep>100);assert(returns>0);console.log(JSON.stringify({returns,pitches,deep,coins:s.coins}));});
console.log(JSON.stringify({v65Tests:passed}));
test('Actual v6.4 upgraded seller and agreed buyer save migrate without losing a single observed record',()=>{for(const old of Object.values(JSON.parse(fs.readFileSync(path.join(__dirname,'migration-v64-fixture.json'))))){const before=copy(old);assert(E.validate(old));E.prepare(old);for(const key of ['coins','stock','relationships','seed','upgrades'])assert.deepEqual(old[key],before[key]);for(const key of ['history','evidence','inspectionResults','inspectionSpent','inspectionLeft','inspectionMax','price','acceptedOffer','buyerQuotes'])assert.deepEqual(old.current[key],before.current[key]);if(old.current.kind==='buyer')assert(old.current.pitchUsed);assert(E.validate(old));const state=JSON.stringify(old);E.prepare(old);assert.equal(JSON.stringify(old),state)}});
console.log(JSON.stringify({v65FinalTests:passed}));
