'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
for(const file of ['items.js','characters.js','profiles.js','appraisal-data.js','item-appraisals.js','voices.js','trade-voice.js','engine.js']){const full=path.join(__dirname,file);if(file==='profiles.js'&&!fs.existsSync(full))continue;vm.runInThisContext(fs.readFileSync(full,'utf8'),{filename:file})}
const E=PawnEngine,copy=x=>JSON.parse(JSON.stringify(x));let tests=0;
function test(name,fn){try{fn();tests++;console.log('PASS '+name)}catch(error){console.error('FAIL '+name);throw error}}
function rejectUnchanged(s,fn){const before=JSON.stringify(s),result=fn();assert.equal(result.ok,false);assert.equal(JSON.stringify(s),before)}
function advance(s){if(s.closing)E.nextDay(s);else E.next(s)}
function seller(seed=123){const s=E.create(seed);s.coins=1000000;return s}
function buyLot(s){assert.equal(s.current.kind,'seller');assert(E.accept(s).ok);return s.stock.at(-1)}
function addLot(s,id='clock-01',overrides={}){const uid='fixture-'+(s.fixture=(s.fixture||0)+1);const lot={uid,itemId:id,grade:2,claimedGrade:2,condition:2,genuine:true,value:300,apparent:300,paid:150,displayAt:null,...overrides};s.stock.push(lot);return lot}
function buyer(seed=551,overrides={}){const s=seller(seed);addLot(s,'clock-01',overrides);addLot(s,'book-01');for(let i=0;i<80&&s.current.kind!=='buyer';i++)advance(s);assert.equal(s.current.kind,'buyer');return s}
test('144 items, 24 people, 24 events and atlas coordinates',()=>{assert.equal(PAWN_ITEMS.length,144);assert.equal(new Set(PAWN_ITEMS.map(x=>x.id)).size,144);assert.equal(PAWN_CHARACTERS.length,24);assert.equal(PAWN_EVENTS.length,24);for(const c of PAWN_CHARACTERS){assert.equal(c.sheet,Math.floor(c.look/8));assert.equal(c.cell,c.look%8)}if(globalThis.PAWN_PROFILES)assert.equal(PAWN_PROFILES.length,24)});
test('Seed determines first visitor, item, evidence and event; first visit is not fixed',()=>{assert.deepEqual(E.create(721),E.create(721));const people=new Set(),goods=new Set(),events=new Set();for(let i=1;i<=80;i++){const s=E.create(i*19381);people.add(s.current.character);goods.add(s.current.itemId);events.add(E.event(s).id);assert.equal(s.current.wasFirst,false);assert(!s.storyQueue);assert(E.validate(s))}assert(people.size>15);assert(goods.size>40);assert(events.size>15)});
test('No immediate customer, seller item or daily event repetition',()=>{const s=E.create(43977);let character=s.current.character,item=s.current.itemId,ev=E.event(s).id;for(let i=0;i<400;i++){if(s.closing){E.nextDay(s);assert.notEqual(E.event(s).id,ev);ev=E.event(s).id}else E.next(s);if(!s.closing){assert.notEqual(s.current.character,character);assert.notEqual(s.current.itemId,item);character=s.current.character;item=s.current.itemId}assert(E.validate(s))}});
test('Read-only views and reload do not reroll evidence, prices, event or seed',()=>{const s=E.create(32911);E.talk(s,'origin');const before=JSON.stringify(s);for(let i=0;i<8;i++){E.profile(s.current.character);E.relationship(s,s.current.character);E.dialogueOptions(s);E.event(s)}assert.equal(JSON.stringify(s),before);const loaded=copy(s);assert(E.validate(loaded));assert.deepEqual(E.prepare(loaded),s);assert.deepEqual(E.prepare(loaded),s)});
test('Authenticity varies per instance and fraud intent is independent of authenticity',()=>{const map=new Map(),seen=new Set(),s=E.create(878989);for(let i=0;i<2400;i++){const o=s.current;const set=map.get(o.itemId)||new Set();set.add(o.genuine);map.set(o.itemId,set);seen.add(o.genuine+':'+o.intent);advance(s)}assert([...map.values()].filter(x=>x.size===2).length>100);for(const key of ['true:honest','true:fraud','false:fraud','false:unaware'])assert(seen.has(key))});
test('Invalid, duplicate and post-agreement money proposals do not mutate state',()=>{const s=seller(720);for(const amount of [0,-1,1.5,NaN,Infinity,'120',null,1e9])rejectUnchanged(s,()=>E.offer(s,amount));const price=s.current.asking;assert(E.offer(s,price).ok);assert(s.current.acceptedOffer);const cash=s.coins;assert.equal(s.stock.length,0);assert.equal(s.coins,cash);rejectUnchanged(s,()=>E.offer(s,price));assert(E.accept(s).ok);rejectUnchanged(s,()=>E.accept(s))});
test('Familiarity improves seller and buyer acceptance conditions',()=>{const plain=seller(719);plain.current.baseFloor=Math.max(80,plain.current.baseFloor);const low=copy(plain),high=copy(plain);low.relationships[low.current.character]=-60;high.relationships[high.current.character]=80;const offered=Math.round(plain.current.baseFloor*.96);assert(E.offer(high,offered).accepted);assert.equal(E.offer(low,offered).accepted,false);const b=buyer(513);const bLow=copy(b),bHigh=copy(b);bLow.relationships[b.current.character]=-60;bHigh.relationships[b.current.character]=80;const ask=Math.round(b.current.buyerQuotes[b.current.stockUid].maxBase*1.04);assert(E.offer(bHigh,ask).accepted);assert.equal(E.offer(bLow,ask).accepted,false)});
test('Buyer item changes cannot reset conversation, patience, mood, attempts or agreement',()=>{const s=buyer(198),first=s.current.stockUid,other=s.stock.find(x=>x.uid!==first).uid;E.talk(s,'taste');E.talk(s,'rapport');E.offer(s,Math.min(E.MAX_OFFER,s.current.price*4));assert.equal(s.current.status,'offered');
const stats=['talkLeft','patience','mood','attempts'].map(k=>s.current[k]);const price=s.current.price,last=s.current.lastOffer,seed=s.seed;assert(E.chooseStock(s,other).ok);assert(E.chooseStock(s,first).ok);assert.deepEqual(['talkLeft','patience','mood','attempts'].map(k=>s.current[k]),stats);assert.equal(s.current.price,price);assert.equal(s.current.lastOffer,last);assert.equal(s.seed,seed);rejectUnchanged(s,()=>E.chooseStock(s,first));rejectUnchanged(s,()=>E.chooseStock(s,'missing'));assert(E.validate(s));assert(E.offer(s,1).accepted);E.chooseStock(s,other);E.chooseStock(s,first);assert(s.current.acceptedOffer);assert.equal(s.current.price,1)});
test('Buyer transaction locks selected stock from other sale routes and completes once',()=>{const s=buyer(211),uid=s.current.stockUid,amount=s.current.price;for(const mode of ['quick','display','request','complete'])rejectUnchanged(s,()=>E.sell(s,uid,mode));const cash=s.coins;const r=E.accept(s);assert(r.ok);assert.equal(r.amount,amount);assert(s.coins>=cash+amount);assert(!s.stock.some(x=>x.uid===uid));rejectUnchanged(s,()=>E.accept(s));rejectUnchanged(s,()=>E.sell(s,uid));assert(E.validate(s))});
test('Buyer with unavailable stock cannot complete or choose it; passing releases lock',()=>{const s=buyer(197),uid=s.current.stockUid;const broken=copy(s);broken.stock=broken.stock.filter(x=>x.uid!==uid);assert(!E.validate(broken));rejectUnchanged(broken,()=>E.accept(broken));E.next(s);if(s.current.kind==='buyer'&&s.current.stockUid===uid)E.next(s);if(s.current.kind==='buyer'&&s.current.stockUid===uid)s.current.status='left';assert(E.sell(s,uid).ok)});
test('Undetected fake can please buyer; voluntary disclosure reduces offer and raises trust',()=>{let unseen;for(let seed=1;seed<1000;seed++){const s=buyer(seed*11,{genuine:false,value:30,apparent:3000});const lot=s.stock.find(x=>x.itemId==='clock-01');if(s.current.stockUid!==lot.uid)E.chooseStock(s,lot.uid);if(!s.current.buyerQuotes[lot.uid].detected){unseen=s;break}}assert(unseen);const honest=copy(unseen),price=honest.current.price,rel=E.relationship(honest,honest.current.character);assert(E.talk(honest,'disclose').ok);assert(honest.current.price<price);assert(E.relationship(honest,honest.current.character)>rel);const before=E.relationship(unseen,unseen.current.character);assert(E.accept(unseen).ok);assert(E.relationship(unseen,unseen.current.character)>before);assert(unseen.current.verdict.includes('진품이라고 믿고'))});
test('Consignment survives reload and completes after exactly two customer advances',()=>{const s=seller(741),lot=buyLot(s);assert(E.sell(s,lot.uid,'display').ok);const expected=lot.displayPrice,cash=s.coins;rejectUnchanged(s,()=>E.sell(s,lot.uid,'complete'));E.next(s);assert.equal(s.coins,cash);const saved=copy(s);assert(E.validate(saved));E.prepare(saved);E.next(saved);assert(!saved.stock.some(x=>x.uid===lot.uid));assert(saved.coins>=cash+expected);rejectUnchanged(saved,()=>E.sell(saved,lot.uid,'complete'))});
test('End-of-day consignment, daily bonus and gift never pay twice',()=>{const s=seller(771);for(let i=0;i<7;i++)E.next(s);s.coins=100000;const lot=buyLot(s);E.sell(s,lot.uid,'display');E.next(s);assert(s.closing);assert(s.stock.some(x=>x.uid===lot.uid));rejectUnchanged(s,()=>E.next(s));const cash=s.coins;E.nextDay(s);assert(s.coins>=cash+85);const dayCash=s.coins;rejectUnchanged(s,()=>E.nextDay(s));assert.equal(s.coins,dayCash);E.next(s);assert(!s.stock.some(x=>x.uid===lot.uid));assert(E.validate(s))});
test('Request reward pays item price plus gift, once only',()=>{const s=seller(122);const lot=buyLot(s);lot.genuine=true;s.activeEvent={id:'fixture',day:s.day,kind:'request',category:'all',mult:1.4,gift:140};s.eventDone=false;const expected=Math.round(lot.value*1.4)+140;const result=E.sell(s,lot.uid,'request');assert(result.ok);assert.equal(result.amount,expected);assert(s.eventDone);const second=addLot(s);rejectUnchanged(s,()=>E.sell(s,second.uid,'request'))});
test('v3 saves migrate once while preserving cash, inventory, collections and current deal',()=>{const s=seller(819);const lot=buyLot(s);const legacy=copy(s);legacy.version=3;delete legacy.relationships;const o=legacy.current;for(const key of ['kind','history','notes','talked','talkLeft','patience','mood','intent','evidence','buyerQuotes','acceptedOffer','baseFloor'])delete o[key];o.checks=['lens','story'];o.clues={lens:'기존에 보아 둔 흔적',story:'이전에 들은 이야기'};legacy.storyQueue=[{id:'clock-return',day:3}];const cash=legacy.coins,stock=copy(legacy.stock),discovery=copy(legacy.discovered),price=o.price;assert(E.validate(legacy));const migrated=E.prepare(legacy);assert.equal(migrated.version,6);assert.equal(migrated.coins,cash);assert.deepEqual(migrated.stock,stock);assert.deepEqual(migrated.discovered,discovery);assert.equal(migrated.current.price,price);assert.equal(migrated.current.status,'bought');assert(!migrated.storyQueue);assert(E.validate(migrated));const serialized=JSON.stringify(migrated);E.prepare(migrated);assert.equal(JSON.stringify(migrated),serialized);assert(E.sell(migrated,lot.uid).ok)});
test('Damaged saves are rejected without mutations',()=>{const original=seller(513),cases=[];let d=copy(original);delete d.current.checks;cases.push(d);d=copy(original);d.current.itemId='missing';cases.push(d);d=copy(original);d.coins=NaN;cases.push(d);d=copy(original);d.relationships[0]=101;cases.push(d);d=copy(original);d.current.talkLeft=200;cases.push(d);const lot=buyLot(original);E.sell(original,lot.uid,'display');d=copy(original);delete d.stock[0].displayPrice;cases.push(d);for(const invalid of cases){const before=JSON.stringify(invalid);assert(!E.validate(invalid));assert.equal(JSON.stringify(invalid),before)}});
test('Empty purse can always continue and recover without a loan lock',()=>{const s=E.create(775);s.coins=0;assert(E.aid(s).ok);assert.equal(s.coins,200);rejectUnchanged(s,()=>E.aid(s));s.coins=0;while(!s.closing)E.next(s);E.nextDay(s);assert(s.coins>0);assert(E.validate(s))});

test('All six investigation controls are identical before and after clues, truth or intent changes',()=>{const s=seller(340);const before=E.investigationOptions(s);assert.equal(before.length,6);assert.deepEqual(new Set(before.map(x=>x.tool)),new Set(['lens','light']));assert(before.every(x=>Object.keys(x).sort().join(',')==='hint,id,label,tool'));const variants=[copy(s),copy(s)];variants[0].current.genuine=false;variants[0].current.intent='fraud';variants[0].current.evidence.disputed=true;variants[1].current.genuine=true;variants[1].current.intent='honest';variants[1].current.evidence.disputed=false;for(const variant of variants){assert.deepEqual(E.investigationOptions(variant),before);E.talk(variant,'origin');E.talk(variant,'detail');assert.deepEqual(E.investigationOptions(variant),before)}assert.deepEqual(E.dialogueOptions(variants[0]).map(x=>x.id),E.dialogueOptions(variants[1]).map(x=>x.id))});
test('Genuine reassurance and a believable fake can raise offers; a knowledgeable buyer rejects false assurance',()=>{const real=buyer(511);const realLot=real.stock.find(x=>x.genuine);if(real.current.stockUid!==realLot.uid)E.chooseStock(real,realLot.uid);const realPrice=real.current.price,realRel=E.relationship(real,real.current.character);assert(E.talk(real,'assert-real').ok);assert(real.current.price>realPrice);assert(E.relationship(real,real.current.character)>realRel);let fooled,caught;for(let seed=1;seed<1500&&(!fooled||!caught);seed++){const s=buyer(seed*41,{genuine:false,value:25,apparent:1400});const fake=s.stock.find(x=>!x.genuine);if(s.current.stockUid!==fake.uid)E.chooseStock(s,fake.uid);const p=E.profile(s.current.character),q=s.current.buyerQuotes[fake.uid];if(!q.detected&&q.assertRoll>=(.16+p.expertise*.68))fooled=s;else caught=s}assert(fooled&&caught);const goodPrice=fooled.current.price,goodRel=E.relationship(fooled,fooled.current.character);E.talk(fooled,'assert-real');assert(fooled.current.price>goodPrice);assert(E.relationship(fooled,fooled.current.character)>goodRel);assert(!fooled.current.buyerQuotes[fooled.current.stockUid].detected);rejectUnchanged(fooled,()=>E.talk(fooled,'assert-real'));const badRel=E.relationship(caught,caught.current.character);E.talk(caught,'assert-real');assert(E.relationship(caught,caught.current.character)<=badRel-15);assert(caught.current.buyerQuotes[caught.current.stockUid].detected);assert(E.validate(caught))});

test('Acceptable offers on different buyer stock do not farm relationship before checkout',()=>{const s=buyer(383),first=s.current.stockUid,second=s.stock.find(x=>x.uid!==first).uid;E.offer(s,1);const earned=E.relationship(s,s.current.character);E.chooseStock(s,second);E.offer(s,1);assert.equal(E.relationship(s,s.current.character),earned);E.chooseStock(s,first);assert.equal(E.relationship(s,s.current.character),earned);assert(E.validate(s))});

function fixture(changes={}){const s=seller(744);Object.assign(s.current,{itemId:'clock-01',genuine:true,grade:3,claimedGrade:3,condition:2,intent:'honest',appraisalClarity:0,talked:[],...changes});delete s.current.investigationVersion;delete s.current.investigations;E.prepare(s);return s}
test('All 144 items have distinct truthful axes with matching public references',()=>{for(const it of PAWN_ITEMS){const s=fixture({itemId:it.id});const cards=E.appraisalNotebook(s);assert.equal(cards.length,3);assert.equal(new Set(Object.values(s.current.evidence.axes).map(a=>a.tool+'-'+a.site)).size,3);for(const c of cards){assert(c.reference.length>20);assert(c.site);assert(c.claim===null||typeof c.claim==='string');assert.equal(c.observation,null)}assert.deepEqual(E.appraisalReview(s),[])}});
test('Only the observed disputed axis supports a challenge; no automatic truth verdict',()=>{const s=fixture({genuine:false,intent:'fraud'});E.talk(s,'authenticity');E.talk(s,'quality');E.investigate(s,'lens-mark');const bad=copy(s),patience=bad.current.patience;rejectUnchanged(bad,()=>E.talk(bad,'challenge-quality'));assert.equal(bad.current.patience,patience);const asking=s.current.asking;E.talk(s,'challenge-authenticity');assert(s.current.asking<asking);assert.equal(s.current.patience,patience);assert(!s.current.notes.some(x=>/모순 발견|가품 확률/.test(x)));assert(E.accept(s).ok);assert.equal(E.appraisalReview(s)[0].result,'모조품')});
test('Faint clues require explicit reinspection after tool upgrade',()=>{const s=fixture({genuine:false,appraisalClarity:2});E.investigate(s,'lens-mark');const a=s.current.evidence.axes.authenticity,first=s.current.inspectionResults['lens-mark'];assert.equal(first,a.unclear);assert(!a.observedActual);E.upgrade(s,'appraisal');E.upgrade(s,'appraisal');E.appraisalNotebook(s);assert.equal(s.current.inspectionResults['lens-mark'],first);E.investigate(s,'lens-mark');assert.equal(s.current.inspectionResults['lens-mark'],a.full);assert(a.observedActual);assert(E.validate(s))});
test('Hidden high craftsmanship only changes seller demand when disclosed',()=>{const s=fixture({grade:7,claimedGrade:3});const price=s.current.price;E.investigate(s,'light-material');assert.equal(s.current.price,price);E.talk(s,'share-findings');assert(s.current.price>price);rejectUnchanged(s,()=>E.talk(s,'share-findings'))});
test('Buyer stories and guarantees follow each item without repeat affection farming',()=>{const s=buyer(433),a=s.current.stockUid,b=s.stock.find(x=>x.uid!==a).uid;E.talk(s,'story');const rel=E.relationship(s,s.current.character);E.chooseStock(s,b);assert(E.dialogueOptions(s).some(x=>x.id==='story'));E.talk(s,'story');assert.equal(E.relationship(s,s.current.character),rel);E.chooseStock(s,a);assert(!E.dialogueOptions(s).some(x=>x.id==='story'));assert(E.validate(s))});
test('Authentic v4 save migrates without losing cash, encounter, agreed price, seed or relations',()=>{const f=path.join(__dirname,'migration-v4-fixture.json');const old=JSON.parse(fs.readFileSync(f)),before=copy(old);assert(E.validate(old));E.prepare(old);assert.equal(old.version,6);for(const k of ['coins','seed','stock','relationships'])assert.deepEqual(old[k],before[k]);for(const k of ['uid','itemId','price','acceptedOffer','patience'])assert.deepEqual(old.current[k],before.current[k]);assert(old.current.legacyHistory.length);assert(E.validate(old));const saved=JSON.stringify(old);E.prepare(old);assert.equal(JSON.stringify(old),saved)});
test('All 24 character voices supply complete lines and explicit monetary acceptance',()=>{for(let i=0;i<24;i++)for(const key of PawnVoice.keys){const line=PawnVoice.say(i,key,{item:'시계',price:321,detail:'작은 선이 세 개입니다.',likes:'시계'});assert(line.length>4);assert(!/\{\w+\}/.test(line));if(key==='offerAccepted')assert(line.includes('321'))}});

test('All 144 item-specific authenticity cases are distinct, complete and connected',()=>{assert.equal(Object.keys(PAWN_ITEM_APPRAISALS).length,144);const good=new Set(),bad=new Set(),sites=new Set(),tools=new Set();for(const it of PAWN_ITEMS){const c=PAWN_ITEM_APPRAISALS[it.id];assert(c);good.add(c.authenticity.observedGenuine);bad.add(c.authenticity.observedReplica);sites.add(c.sites.mark.label);tools.add(c.authenticity.tool);for(const genuine of [true,false]){const s=fixture({itemId:it.id,genuine,intent:'fraud'});assert.equal(s.current.appraisalEdition,51);const a=s.current.evidence.axes.authenticity;assert.equal(a.tool,c.authenticity.tool);assert.equal(a.full,genuine?c.authenticity.observedGenuine:c.authenticity.observedReplica);assert(c.authenticity.reference.includes(a.full));E.talk(s,'authenticity');assert(s.current.history.at(-1).text.includes(PawnTradeVoice.spoken(c.authenticity.claimGenuine,s.current.character)));E.investigate(s,a.tool+'-'+a.site);assert.equal(E.appraisalNotebook(s)[0].observation,a.full);if(!genuine){const price=s.current.price;E.talk(s,'challenge-authenticity');assert(s.current.price<price)}}for(const key of ['quality','condition']){assert.equal(c[key].claims.length,3);assert.equal(c[key].observations.length,3);assert(c[key].question.includes(c.sites[c[key].site].label));assert(c[key].reference.includes(c.sites[c[key].site].label));for(const observation of c[key].observations)assert(observation.includes(c.sites[c[key].site].label));}}assert.equal(good.size,144);assert.equal(bad.size,144);assert.equal(sites.size,144);assert.equal(tools.size,2)});
test('Item-specific clues stay stable through upgrades, reload and read-only UI',()=>{const s=fixture({itemId:'toy-08',appraisalClarity:2,genuine:false});E.talk(s,'authenticity');E.investigate(s,'lens-mark');const first=s.current.inspectionResults['lens-mark'];const before=JSON.stringify(s);for(let i=0;i<5;i++){E.prepare(s);E.appraisalNotebook(s);E.dialogueOptions(s);E.investigationOptions(s)}assert.equal(JSON.stringify(s),before);E.upgrade(s,'appraisal');E.upgrade(s,'appraisal');assert.equal(s.current.inspectionResults['lens-mark'],first);E.investigate(s,'lens-mark');assert.equal(s.current.inspectionResults['lens-mark'],PAWN_ITEM_APPRAISALS['toy-08'].authenticity.observedReplica);assert(E.validate(s))});


test('Exactly two exploratory questions and two investigations; cached rereads are free',()=>{const s=fixture(),patience=s.current.patience;assert.equal(s.current.talkLeft,2);assert(E.talk(s,'authenticity').ok);assert(E.talk(s,'quality').ok);rejectUnchanged(s,()=>E.talk(s,'condition'));assert.equal(s.current.talkLeft,0);E.investigate(s,'lens-mark');E.investigate(s,'light-material');assert.equal(s.current.inspectionLeft,0);rejectUnchanged(s,()=>E.investigate(s,'lens-wear'));const saved=JSON.stringify(s);assert(E.investigate(s,'lens-mark').repeated);assert.equal(JSON.stringify(s),saved);assert.equal(s.current.patience,patience);assert(E.validate(s))});
test('A wrong tool spends investigation opportunity and produces no supported bargaining evidence',()=>{const s=fixture({genuine:false}),price=s.current.price;E.investigate(s,'light-mark');assert.equal(s.current.inspectionLeft,1);rejectUnchanged(s,()=>E.presentEvidence(s,'authenticity','defect'));assert.equal(s.current.price,price);E.investigate(s,'lens-mark');assert(E.presentEvidence(s,'authenticity','defect').supported);assert(s.current.price<price)});
test('Player assumptions change estimates but never reveal or mutate hidden truth',()=>{const a=fixture({genuine:false}),b=copy(a);b.current.genuine=true;b.current.grade=8;b.current.value=123456;assert.deepEqual(E.valuation(a),E.valuation(b));const price=a.current.price,seed=a.seed;E.judge(a,'authenticity',1);E.judge(a,'quality',2);E.judge(a,'condition',2);const high=E.valuation(a);E.judge(a,'authenticity',0);const low=E.valuation(a);assert(low.max<high.max);assert.equal(a.current.price,price);assert.equal(a.seed,seed);assert.equal(a.current.genuine,false);rejectUnchanged(a,()=>E.judge(a,'quality',9));assert(E.validate(a))});
test('Confirmed defects change asking price and floor, even when a previously disclosed flaw is used',()=>{for(const [key,changes] of [['authenticity',{genuine:false}],['quality',{grade:0,claimedGrade:0}],['condition',{condition:0}]]){const s=fixture(changes),a=s.current.evidence.axes[key];E.investigate(s,a.tool+'-'+a.site);const price=s.current.price,floor=s.current.baseFloor,questions=s.current.talkLeft;assert(E.presentEvidence(s,key,'defect').supported);assert(s.current.price<price);assert(s.current.baseFloor<floor);assert.equal(s.current.lastImpact.before,price);assert.equal(s.current.lastImpact.after,s.current.price);assert.equal(s.current.talkLeft,questions);assert(s.current.history.some(h=>h.speaker==='customer'&&h.text.includes(s.current.price.toLocaleString('ko-KR'))));rejectUnchanged(s,()=>E.presentEvidence(s,key,'defect'));assert(E.validate(s))}});
test('Good craftsmanship can be kept private or disclosed for a visible price/trust tradeoff',()=>{const s=fixture({grade:6,claimedGrade:3}),price=s.current.price,relation=E.relationship(s,s.current.character);E.investigate(s,'light-material');E.judge(s,'quality',2);assert.equal(s.current.price,price);assert.equal(E.relationship(s,s.current.character),relation);const disclosed=copy(s);assert(E.presentEvidence(disclosed,'quality','praise').supported);assert.equal(disclosed.current.price,Math.round(price*1.25));assert.equal(E.relationship(disclosed,disclosed.current.character),relation+5);assert.equal(s.current.price,price);assert.equal(disclosed.current.lastImpact.relationDelta,5);const known=fixture({grade:6,claimedGrade:6});E.investigate(known,'light-material');const original=known.current.price;assert(E.presentEvidence(known,'quality','praise').supported);assert.equal(known.current.price,original);assert.equal(known.current.lastImpact.relationDelta,2)});
test('Unfounded defect lowers patience and relationship; groundless praise has an explicit neutral outcome',()=>{const s=fixture(),price=s.current.price,rel=E.relationship(s,s.current.character),patience=s.current.patience;E.investigate(s,'lens-mark');assert.equal(E.presentEvidence(s,'authenticity','defect').supported,false);assert.equal(s.current.price,price);assert.equal(s.current.patience,patience-1);assert.equal(E.relationship(s,s.current.character),rel-5);const q=fixture({grade:0});E.investigate(q,'light-material');assert.equal(E.presentEvidence(q,'quality','praise').supported,false);assert.equal(q.current.lastImpact.relationDelta,0);assert.equal(q.current.lastImpact.before,q.current.lastImpact.after)});
test('Inspecting and judging all truth/quality/condition combinations requires choosing priorities',()=>{for(const genuine of [true,false])for(const grade of [0,3,7])for(const condition of [0,2,4])for(const key of ['authenticity','quality','condition']){const s=fixture({genuine,grade,condition}),a=s.current.evidence.axes[key];E.talk(s,key);E.investigate(s,a.tool+'-'+a.site);assert.equal(s.current.inspectionResults[a.tool+'-'+a.site],a.full);assert.equal(s.current.talkLeft,1);assert.equal(s.current.inspectionLeft,1);assert(E.validate(s))}});
test('V5 migration preserves evidence and money while installing only unused action opportunities',()=>{const s=JSON.parse(fs.readFileSync(path.join(__dirname,'migration-v5-fixture.json'),'utf8')),old=copy(s);assert(E.validate(s));E.prepare(s);assert.equal(s.version,6);assert.equal(s.coins,old.coins);assert.equal(s.seed,old.seed);for(const k of ['evidence','history','inspectionResults','price','acceptedOffer'])assert.deepEqual(s.current[k],old.current[k]);assert.equal(s.current.talkLeft,1);assert.equal(s.current.inspectionLeft,1);assert(E.appraisalNotebook(s)[0].reference.includes('초승달'));const before=JSON.stringify(s);E.prepare(s);assert.equal(JSON.stringify(s),before);assert(E.validate(s));E.next(s);assert.equal(s.current.appraisalEdition,51);assert.equal(s.current.talkLeft,2);assert.equal(s.current.inspectionLeft,2)});
test('Appraisal upgrade grants a third investigation on future visits only',()=>{const s=fixture();E.upgrade(s,'appraisal');E.upgrade(s,'appraisal');E.upgrade(s,'appraisal');assert.equal(s.current.inspectionMax,2);E.next(s);assert.equal(s.current.inspectionMax,3);assert.equal(s.current.inspectionLeft,3);assert(E.validate(s))});
test('Actual profits follow purchase and sale, while a forecast is preserved at purchase',()=>{const s=fixture({grade:6,claimedGrade:3});s.current.value=691;s.current.price=250;E.judge(s,'authenticity',1);E.judge(s,'quality',2);const forecast=E.valuation(s);const startProfit=s.profit;assert(E.accept(s).ok);assert.deepEqual(s.current.purchasePrediction,forecast);assert.equal(s.profit,startProfit);const lot=s.stock.at(-1),quoted=E.quote(s,lot);assert(E.sell(s,lot.uid).ok);assert.equal(s.profit,startProfit+quoted-250);assert(E.validate(s))});

test('All three goals progress independently and changing focus preserves records',()=>{const s=seller();s.profit=3500;s.album['clock-01']={day:1,grade:3};s.relationships[0]=30;const before=copy(s);for(const id of ['collection','friends','profit'])assert(E.setAmbition(s,id).ok);assert.equal(s.profit,before.profit);assert.deepEqual(s.album,before.album);const g=E.goals(s);assert.equal(g[0].completed,2);assert.equal(g[1].value,1);assert.equal(g[2].value,1);rejectUnchanged(s,()=>E.setAmbition(s,'wrong'))});
function closeDay(s){s.visitor=8;s.current.status='left';E.next(s);assert.equal(s.night.actions,2)}
test('Night grants only two actions, persists on reload, and resets only on next closing',()=>{const s=seller();addLot(s);rejectUnchanged(s,()=>E.nightAction(s,'catalog',s.stock[0].uid));closeDay(s);assert(E.nightAction(s,'catalog',s.stock[0].uid).ok);assert.equal(s.night.actions,1);const load=E.prepare(copy(s));assert.deepEqual(load,s);assert(E.nightAction(load,'tea',String(load.current.character)).ok);assert.equal(load.night.actions,0);rejectUnchanged(load,()=>E.nightAction(load,'repair',load.stock[0].uid));const old=copy(load.album);E.nextDay(load);assert.equal(load.night,null);assert.deepEqual(load.album,old);closeDay(load);assert.equal(load.night.actions,2);assert(E.validate(load))});
test('Catalog requires a genuine available item and keeps permanent records after sale',()=>{const s=seller(),real=addLot(s),fake=addLot(s,'book-01',{genuine:false}),waiting=addLot(s,'toy-01',{displayAt:99,displayPrice:350});closeDay(s);rejectUnchanged(s,()=>E.nightAction(s,'catalog',fake.uid));rejectUnchanged(s,()=>E.nightAction(s,'catalog',waiting.uid));assert(E.nightAction(s,'catalog',real.uid).ok);assert(s.stock.includes(real));rejectUnchanged(s,()=>E.nightAction(s,'catalog',real.uid));E.sell(s,real.uid);assert(s.album[real.itemId]);assert(E.validate(s))});
test('Every themed collection pays once and reveals its story after its fourth registration',()=>{for(const set of E.COLLECTIONS){const s=seller();for(const id of set.items.slice(0,3))s.album[id]={day:1,grade:2};const lot=addLot(s,set.items[3]);closeDay(s);const cash=s.coins;assert(E.nightAction(s,'catalog',lot.uid).ok);assert.equal(s.coins,cash+120);assert(s.albumRewards.includes(set.id));assert(s.night.report[0].includes(set.story));rejectUnchanged(s,()=>E.nightAction(s,'catalog',lot.uid));assert(E.validate(E.prepare(copy(s))))}});
test('Tea unlocks a persistent personal story and cannot repeat for one guest in a night',()=>{const s=seller(),i=s.current.character;s.relationships[i]=20;closeDay(s);const cash=s.coins;assert(E.nightAction(s,'tea',String(i)).ok);assert.equal(s.coins,cash-25);assert.equal(E.relationship(s,i),26);assert(s.friendStories.includes(i));rejectUnchanged(s,()=>E.nightAction(s,'tea',String(i)));s.relationships[i]=0;E.prepare(s);assert(s.friendStories.includes(i));assert(E.validate(s))});
test('Repair raises condition and value but charges cost into eventual profit; fakes remain fakes',()=>{for(const genuine of [true,false]){const s=seller(),lot=addLot(s,'clock-01',{genuine,condition:0,value:720,apparent:1440,paid:400});closeDay(s);const q=E.repairQuote(s,lot),cash=s.coins;assert(E.nightAction(s,'repair',lot.uid).ok);assert.equal(lot.condition,1);assert.equal(lot.value,880);assert.equal(lot.genuine,genuine);assert.equal(s.coins,cash-q.cost);assert.equal(lot.paid,400+q.cost);rejectUnchanged(s,()=>E.nightAction(s,'repair',lot.uid));const profit=s.profit,price=E.quote(s,lot);E.sell(s,lot.uid);assert.equal(s.profit-profit,price-400-q.cost);assert(E.validate(s))}});
test('Unfunded, invalid and impossible night actions neither spend time nor alter records',()=>{const s=seller(),lot=addLot(s,'clock-01',{condition:4});closeDay(s);s.coins=0;rejectUnchanged(s,()=>E.nightAction(s,'tea',String(s.current.character)));rejectUnchanged(s,()=>E.nightAction(s,'repair',lot.uid));rejectUnchanged(s,()=>E.nightAction(s,'catalog','missing'));assert.equal(s.night.actions,2);assert(E.nightAction(s,'catalog',lot.uid).ok);assert(E.validate(s))});
test('Closing v5 save migrates to night activities once without granting extra time on reload',()=>{const s=JSON.parse(fs.readFileSync(path.join(__dirname,'migration-v5-fixture.json'),'utf8'));s.visitor=8;s.current.status='left';s.closing=true;assert(E.validate(s));E.prepare(s);assert.equal(s.night.actions,2);E.nightAction(s,'tea',String(s.current.character));const serialized=JSON.stringify(s);E.prepare(s);assert.equal(JSON.stringify(s),serialized);assert(E.validate(s))});
const stats={visits:0,sellers:0,buyers:0,fakes:0,unaware:0,fraud:0,genuineFraud:0,jackpots:0,grades:new Set()};
test('3000 mixed encounters preserve invariants, save continuity and meaningful authenticity risk',()=>{let s=E.create(4438271);for(let i=0;i<3000;i++){if(s.closing)E.nextDay(s);s.coins=10000000;const o=s.current;stats.visits++;if(o.kind==='seller'){stats.sellers++;stats.grades.add(o.grade);if(!o.genuine)stats.fakes++;if(o.intent==='unaware')stats.unaware++;if(o.intent==='fraud')stats.fraud++;if(o.genuine&&o.intent==='fraud')stats.genuineFraud++;if(o.sleeper)stats.jackpots++;if(i%3===0)E.investigate(s,E.investigationOptions(s)[i%6].id);const opts=E.dialogueOptions(s);if(opts.length)E.talk(s,opts[i%opts.length].id);const result=E.accept(s);if(result.ok&&i%3===0)E.sell(s,o.uid,i%2?'display':'quick')}else{stats.buyers++;if(i%3===0)E.talk(s,'taste');if(i%7===0)E.offer(s,Math.max(1,Math.round(o.price*1.15)));if(s.current.status==='offered')E.accept(s)}if(s.stock.length>12){const spare=s.stock.find(x=>x.displayAt===null&&!(s.current.kind==='buyer'&&s.current.status==='offered'&&s.current.stockUid===x.uid));if(spare)E.sell(s,spare.uid)}assert(E.validate(s),'Invalid after visit '+i);if(i%17===0){const serialized=JSON.stringify(s);s=E.prepare(JSON.parse(serialized));assert.equal(JSON.stringify(s),serialized)}E.next(s);assert(E.validate(s),'Invalid after advance '+i)}assert(stats.buyers>500);assert(stats.fakes>250);assert(stats.unaware>100);assert(stats.genuineFraud>100);assert(stats.jackpots>100);assert.equal(stats.grades.size,9)});
console.log(JSON.stringify({tests,stats:{...stats,grades:[...stats.grades].sort()}},null,2));